# Generated by Django 5.2.14 on 2026-06-03 20:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('cards', '0010_alter_card_background_color_alter_card_barcode_type_and_more'),
        ('customers', '0010_alter_applepassregistration_customer_pass_and_more'),
        ('tenants', '0011_alter_location_address_alter_location_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeranalytics',
            name='active_passes',
            field=models.PositiveIntegerField(default=0, help_text='Number of currently active passes.', verbose_name='Pases activos'),
        ),
        migrations.AlterField(
            model_name='customeranalytics',
            name='average_transaction',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Average transaction amount.', max_digits=10, verbose_name='Transacción promedio'),
        ),
        migrations.AlterField(
            model_name='customeranalytics',
            name='customer',
            field=models.OneToOneField(help_text='The customer associated with this record.', on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='customers.customer', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='customeranalytics',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customeranalytics',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, help_text='Last updated.', verbose_name='Última actualización'),
        ),
        migrations.AlterField(
            model_name='customeranalytics',
            name='segment',
            field=models.CharField(choices=[('high_value', 'Alto valor'), ('regular', 'Regular'), ('at_risk', 'En riesgo'), ('new', 'Nuevo'), ('inactive', 'Inactivo')], default='new', help_text='Customer engagement segment.', max_length=20, verbose_name='Segmento'),
        ),
        migrations.AlterField(
            model_name='customeranalytics',
            name='tenant',
            field=models.ForeignKey(help_text='The business this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='customer_analytics', to='tenants.tenant', verbose_name='Negocio'),
        ),
        migrations.AlterField(
            model_name='customeranalytics',
            name='total_passes',
            field=models.PositiveIntegerField(default=0, help_text='Total number of passes held.', verbose_name='Total de pases'),
        ),
        migrations.AlterField(
            model_name='customeranalytics',
            name='total_rewards_earned',
            field=models.PositiveIntegerField(default=0, help_text='Total rewards earned.', verbose_name='Recompensas ganadas'),
        ),
        migrations.AlterField(
            model_name='customeranalytics',
            name='total_rewards_redeemed',
            field=models.PositiveIntegerField(default=0, help_text='Total rewards redeemed.', verbose_name='Recompensas canjeadas'),
        ),
        migrations.AlterField(
            model_name='customeranalytics',
            name='total_spent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total amount spent.', max_digits=12, verbose_name='Total gastado'),
        ),
        migrations.AlterField(
            model_name='customeranalytics',
            name='total_visits',
            field=models.PositiveIntegerField(default=0, help_text='Total number of visits recorded.', verbose_name='Total de visitas'),
        ),
        migrations.AlterField(
            model_name='dailyanalytics',
            name='analytics_date',
            field=models.DateField(db_index=True, help_text='Date of the analytics snapshot.', verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='dailyanalytics',
            name='daily_revenue',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Revenue recorded on this date.', max_digits=12, verbose_name='Ingresos diarios'),
        ),
        migrations.AlterField(
            model_name='dailyanalytics',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dailyanalytics',
            name='new_customers',
            field=models.PositiveIntegerField(default=0, help_text='Number of new customers.', verbose_name='Nuevos clientes'),
        ),
        migrations.AlterField(
            model_name='dailyanalytics',
            name='new_enrollments',
            field=models.PositiveIntegerField(default=0, help_text='Number of new enrollments.', verbose_name='Nuevas inscripciones'),
        ),
        migrations.AlterField(
            model_name='dailyanalytics',
            name='notifications_sent',
            field=models.PositiveIntegerField(default=0, help_text='Number of notifications sent.', verbose_name='Notificaciones enviadas'),
        ),
        migrations.AlterField(
            model_name='dailyanalytics',
            name='rewards_issued',
            field=models.PositiveIntegerField(default=0, help_text='Number of rewards issued.', verbose_name='Recompensas emitidas'),
        ),
        migrations.AlterField(
            model_name='dailyanalytics',
            name='rewards_redeemed',
            field=models.PositiveIntegerField(default=0, help_text='Number of rewards redeemed.', verbose_name='Recompensas canjeadas'),
        ),
        migrations.AlterField(
            model_name='dailyanalytics',
            name='tenant',
            field=models.ForeignKey(help_text='The business this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='daily_analytics', to='tenants.tenant', verbose_name='Negocio'),
        ),
        migrations.AlterField(
            model_name='dailyanalytics',
            name='transactions',
            field=models.PositiveIntegerField(default=0, help_text='Number of transactions.', verbose_name='Transacciones'),
        ),
        migrations.AlterField(
            model_name='programanalytics',
            name='active_members',
            field=models.PositiveIntegerField(default=0, help_text='Number of active members.', verbose_name='Miembros activos'),
        ),
        migrations.AlterField(
            model_name='programanalytics',
            name='average_order_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Average order value.', max_digits=10, verbose_name='Valor promedio de pedido'),
        ),
        migrations.AlterField(
            model_name='programanalytics',
            name='card',
            field=models.OneToOneField(help_text='The loyalty program associated with this record.', on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='cards.card', verbose_name='Programa'),
        ),
        migrations.AlterField(
            model_name='programanalytics',
            name='engagement_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Percentage of enrolled members active.', max_digits=5, verbose_name='Tasa de participación %'),
        ),
        migrations.AlterField(
            model_name='programanalytics',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='programanalytics',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, help_text='Last updated.', verbose_name='Última actualización'),
        ),
        migrations.AlterField(
            model_name='programanalytics',
            name='redemption_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Percentage of issued rewards redeemed.', max_digits=5, verbose_name='Tasa de canje %'),
        ),
        migrations.AlterField(
            model_name='programanalytics',
            name='repeat_purchase_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Percentage of members with repeat purchases.', max_digits=5, verbose_name='Tasa de recompra %'),
        ),
        migrations.AlterField(
            model_name='programanalytics',
            name='tenant',
            field=models.ForeignKey(help_text='The business this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='program_analytics', to='tenants.tenant', verbose_name='Negocio'),
        ),
        migrations.AlterField(
            model_name='programanalytics',
            name='total_enrollments',
            field=models.PositiveIntegerField(default=0, help_text='Total customer enrollments.', verbose_name='Total de inscritos'),
        ),
        migrations.AlterField(
            model_name='programanalytics',
            name='total_revenue',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total cumulative revenue.', max_digits=12, verbose_name='Ingresos totales'),
        ),
        migrations.AlterField(
            model_name='programanalytics',
            name='total_rewards_issued',
            field=models.PositiveIntegerField(default=0, help_text='Total rewards issued.', verbose_name='Recompensas emitidas'),
        ),
        migrations.AlterField(
            model_name='programanalytics',
            name='total_rewards_redeemed',
            field=models.PositiveIntegerField(default=0, help_text='Total rewards redeemed.', verbose_name='Recompensas canjeadas'),
        ),
        migrations.AlterField(
            model_name='programanalytics',
            name='total_transactions',
            field=models.PositiveIntegerField(default=0, help_text='Total transactions.', verbose_name='Total de transacciones'),
        ),
    ]
