# Generated by Django 5.0.6 on 2026-04-06 15:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('card_type', models.CharField(choices=[('stamp', 'Tarjeta de Sellos'), ('cashback', 'Tarjeta de Cashback'), ('coupon', 'Tarjeta de Cupón'), ('affiliate', 'Tarjeta de Afiliación'), ('discount', 'Tarjeta de Descuento'), ('gift_certificate', 'Certificado de Regalo'), ('vip_membership', 'Membresía VIP'), ('corporate_discount', 'Descuento Corporativo'), ('referral_pass', 'Programa de Referidos'), ('multipass', 'Multipase')], max_length=20, verbose_name='Tipo de tarjeta')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del programa')),
                ('description', models.TextField(blank=True, default='', verbose_name='Descripción')),
                ('logo_url', models.URLField(blank=True, default='', verbose_name='URL del logo')),
                ('background_color', models.CharField(default='#1a1a2e', max_length=7, verbose_name='Color de fondo (HEX)')),
                ('text_color', models.CharField(default='#ffffff', max_length=7, verbose_name='Color del texto (HEX)')),
                ('strip_image_url', models.URLField(blank=True, default='', verbose_name='Imagen de tira')),
                ('icon_url', models.URLField(blank=True, default='', verbose_name='URL del ícono')),
                ('is_active', models.BooleanField(default=True, verbose_name='Programa activo')),
                ('metadata', models.JSONField(default=dict, verbose_name='Configuración específica')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='tenants.tenant', verbose_name='Negocio')),
            ],
            options={
                'verbose_name': 'Programa de fidelización',
                'verbose_name_plural': 'Programas de fidelización',
                'db_table': 'loyallia_cards',
                'ordering': ['-created_at'],
                'unique_together': {('tenant', 'name')},
            },
        ),
    ]
