# Generated by Django 5.0.6 on 2026-04-06 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="locations",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Ubicaciones (Geofencing)"
            ),
        ),
    ]
