# Generated by Plan B production recovery on 2026-05-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0004_card_idx_card_tenant_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="stamps_required",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                verbose_name="Sellos requeridos",
            ),
        ),
        migrations.AddField(
            model_name="card",
            name="cashback_percentage",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Porcentaje cashback",
            ),
        ),
        migrations.AddField(
            model_name="card",
            name="minimum_purchase",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=10,
                null=True,
                verbose_name="Compra mínima",
            ),
        ),
        migrations.AddField(
            model_name="card",
            name="credit_expiry_days",
            field=models.PositiveIntegerField(
                blank=True,
                default=365,
                null=True,
                verbose_name="Días de expiración de crédito",
            ),
        ),
    ]
