# Generated by Django 5.0.6 on 2026-05-01 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0005_card_typed_configuration_fields"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="card",
            name="idx_card_tenant_active",
        ),
    ]
