# Generated by Django 5.0.6 on 2026-05-18 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0006_remove_card_idx_card_tenant_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="icon_url",
            field=models.URLField(
                blank=True, default="", max_length=2000, verbose_name="URL del ícono"
            ),
        ),
        migrations.AlterField(
            model_name="card",
            name="logo_url",
            field=models.URLField(
                blank=True, default="", max_length=2000, verbose_name="URL del logo"
            ),
        ),
        migrations.AlterField(
            model_name="card",
            name="strip_image_url",
            field=models.URLField(
                blank=True, default="", max_length=2000, verbose_name="Imagen de tira"
            ),
        ),
    ]
