# Generated by Django 5.2.14 on 2026-06-03 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0009_card_redemption_rules'),
        ('tenants', '0011_alter_location_address_alter_location_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='background_color',
            field=models.CharField(default='#1a1a2e', help_text='Background color in HEX format.', max_length=7, verbose_name='Color de fondo (HEX)'),
        ),
        migrations.AlterField(
            model_name='card',
            name='barcode_type',
            field=models.CharField(choices=[('qr_code', 'Código QR'), ('aztec', 'Aztec'), ('code_128', 'Code 128'), ('pdf417', 'PDF417'), ('data_matrix', 'Data Matrix')], default='qr_code', help_text='Type of barcode used for passes.', max_length=20, verbose_name='Tipo de código de barras'),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_type',
            field=models.CharField(choices=[('stamp', 'Tarjeta de Sellos'), ('cashback', 'Tarjeta de Cashback'), ('coupon', 'Tarjeta de Cupón'), ('affiliate', 'Tarjeta de Afiliación'), ('discount', 'Tarjeta de Descuento'), ('gift_certificate', 'Certificado de Regalo'), ('vip_membership', 'Membresía VIP'), ('corporate_discount', 'Descuento Corporativo'), ('referral_pass', 'Programa de Referidos'), ('multipass', 'Multipase')], help_text='Type of loyalty program.', max_length=20, verbose_name='Tipo de tarjeta'),
        ),
        migrations.AlterField(
            model_name='card',
            name='cashback_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Percentage of purchase returned as cashback.', max_digits=5, null=True, verbose_name='Porcentaje cashback'),
        ),
        migrations.AlterField(
            model_name='card',
            name='credit_expiry_days',
            field=models.PositiveIntegerField(blank=True, default=365, help_text='Days until earned credit expires.', null=True, verbose_name='Días de expiración de crédito'),
        ),
        migrations.AlterField(
            model_name='card',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Description of this record.', verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='card',
            name='icon_url',
            field=models.URLField(blank=True, default='', help_text='URL of the icon image.', max_length=2000, verbose_name='URL del ícono'),
        ),
        migrations.AlterField(
            model_name='card',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this record is currently active.', verbose_name='Programa activo'),
        ),
        migrations.AlterField(
            model_name='card',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Whether this program is publicly visible.', verbose_name='Programa publicado'),
        ),
        migrations.AlterField(
            model_name='card',
            name='locations',
            field=models.JSONField(blank=True, default=list, help_text='Geographic locations stored as JSON.', verbose_name='Ubicaciones (Geofencing)'),
        ),
        migrations.AlterField(
            model_name='card',
            name='logo_url',
            field=models.URLField(blank=True, default='', help_text='URL of the logo image.', max_length=2000, verbose_name='URL del logo'),
        ),
        migrations.AlterField(
            model_name='card',
            name='metadata',
            field=models.JSONField(default=dict, help_text='Additional configuration stored as JSON.', verbose_name='Configuración específica'),
        ),
        migrations.AlterField(
            model_name='card',
            name='minimum_purchase',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Minimum purchase amount required.', max_digits=10, null=True, verbose_name='Compra mínima'),
        ),
        migrations.AlterField(
            model_name='card',
            name='name',
            field=models.CharField(help_text='Name of this record.', max_length=100, verbose_name='Nombre del programa'),
        ),
        migrations.AlterField(
            model_name='card',
            name='stamps_required',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Number of stamps required for a reward.', null=True, verbose_name='Sellos requeridos'),
        ),
        migrations.AlterField(
            model_name='card',
            name='strip_image_url',
            field=models.URLField(blank=True, default='', help_text='URL of the strip image.', max_length=2000, verbose_name='Imagen de tira'),
        ),
        migrations.AlterField(
            model_name='card',
            name='tenant',
            field=models.ForeignKey(help_text='The business this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='tenants.tenant', verbose_name='Negocio'),
        ),
        migrations.AlterField(
            model_name='card',
            name='text_color',
            field=models.CharField(default='#ffffff', help_text='Text color in HEX format.', max_length=7, verbose_name='Color del texto (HEX)'),
        ),
    ]
