# Generated by Django 5.2.14 on 2026-06-03 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0011_card_created_by_card_updated_by'),
        ('tenants', '0011_alter_location_address_alter_location_city_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['tenant', 'is_active'], name='loyallia_ca_tenant__90dc30_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['tenant', 'card_type'], name='loyallia_ca_tenant__b43fcb_idx'),
        ),
    ]
