sentinel monitor loyallia-master redis 6379 2
sentinel down-after-milliseconds loyallia-master 5000
sentinel failover-timeout loyallia-master 60000
sentinel parallel-syncs loyallia-master 1
sentinel auth-pass loyallia-master ${REDIS_PASSWORD}
