# Generated by Django 5.0.6 on 2026-04-06 15:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("reward_earned", "Reward Earned"),
                            ("reward_ready", "Reward Ready for Redemption"),
                            ("special_offer", "Special Offer"),
                            ("reminder", "Reminder to Visit"),
                            ("milestone", "Milestone Reached"),
                            ("birthday", "Birthday Offer"),
                            ("system", "System Notification"),
                            ("marketing", "Marketing Campaign"),
                        ],
                        max_length=30,
                        verbose_name="Tipo de notificación",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("push", "Push Notification"),
                            ("sms", "SMS"),
                            ("email", "Email"),
                            ("in_app", "In-App Notification"),
                        ],
                        default="push",
                        max_length=20,
                        verbose_name="Canal",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Título")),
                ("message", models.TextField(verbose_name="Mensaje")),
                (
                    "image_url",
                    models.URLField(
                        blank=True, default="", verbose_name="URL de imagen"
                    ),
                ),
                (
                    "action_url",
                    models.URLField(
                        blank=True, default="", verbose_name="URL de acción"
                    ),
                ),
                (
                    "notification_data",
                    models.JSONField(default=dict, verbose_name="Datos adicionales"),
                ),
                ("is_sent", models.BooleanField(default=False, verbose_name="Enviado")),
                ("is_read", models.BooleanField(default=False, verbose_name="Leído")),
                (
                    "is_clicked",
                    models.BooleanField(default=False, verbose_name="Clickeado"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de envío"
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de lectura"
                    ),
                ),
                (
                    "clicked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de click"
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="customers.customer",
                        verbose_name="Cliente",
                    ),
                ),
                (
                    "customer_pass",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="customers.customerpass",
                        verbose_name="Pase del cliente",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="tenants.tenant",
                        verbose_name="Negocio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notificación",
                "verbose_name_plural": "Notificaciones",
                "db_table": "loyallia_notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["customer", "-created_at"],
                        name="loyallia_no_custome_aaf869_idx",
                    ),
                    models.Index(
                        fields=["is_sent", "is_read"],
                        name="loyallia_no_is_sent_bd14c2_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PushDevice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("ios", "iOS"),
                            ("android", "Android"),
                            ("web", "Web"),
                        ],
                        max_length=10,
                        verbose_name="Tipo de dispositivo",
                    ),
                ),
                (
                    "device_token",
                    models.CharField(
                        max_length=500, verbose_name="Token del dispositivo"
                    ),
                ),
                (
                    "device_model",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="Modelo del dispositivo",
                    ),
                ),
                (
                    "apns_token",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="Token APNS",
                    ),
                ),
                (
                    "fcm_token",
                    models.CharField(
                        blank=True, default="", max_length=500, verbose_name="Token FCM"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="Dispositivo activo"
                    ),
                ),
                (
                    "push_failures",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Incremented per failed push; device deactivated at 5",
                        verbose_name="Fallos consecutivos de push",
                    ),
                ),
                (
                    "registered_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de registro"
                    ),
                ),
                (
                    "last_used",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Último uso"
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to="customers.customer",
                        verbose_name="Cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dispositivo de push",
                "verbose_name_plural": "Dispositivos de push",
                "db_table": "loyallia_push_devices",
                "ordering": ["-registered_at"],
                "unique_together": {("customer", "device_token")},
            },
        ),
    ]
