# Generated by Django 5.0.6 on 2026-05-01 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_notification_idx_notif_tenant_type"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="notification",
            name="idx_notif_tenant_type",
        ),
    ]
