# Generated by Django 5.0.6 on 2026-05-05 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0004_alter_notification_channel_campaignrun_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="whatsappsession",
            name="daily_limit_override",
            field=models.PositiveIntegerField(
                default=0,
                help_text="SuperAdmin override. 0=use plan limit. Max safe value: 200.",
                verbose_name="Override límite diario",
            ),
        ),
        migrations.AlterField(
            model_name="whatsappsession",
            name="daily_limit",
            field=models.IntegerField(
                default=200, verbose_name="Límite diario (legacy)"
            ),
        ),
    ]
