# Generated by Django 5.2.14 on 2026-06-02 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0009_card_redemption_rules"),
        ("customers", "0009_customerpass_coupon_redemption_count_and_more"),
        ("notifications", "0007_alter_notification_customer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaignrun",
            name="target_customers",
            field=models.ManyToManyField(
                blank=True,
                related_name="targeted_campaigns",
                to="customers.customer",
                verbose_name="Clientes objetivo",
            ),
        ),
        migrations.AddField(
            model_name="campaignrun",
            name="target_device_types",
            field=models.CharField(
                choices=[
                    ("ios", "iOS"),
                    ("android", "Android"),
                    ("both", "Ambos"),
                    ("none", "Ninguno"),
                ],
                default="both",
                max_length=20,
                verbose_name="Tipos de dispositivo objetivo",
            ),
        ),
        migrations.AddField(
            model_name="campaignrun",
            name="target_programs",
            field=models.ManyToManyField(
                blank=True,
                related_name="campaigns",
                to="cards.card",
                verbose_name="Programas objetivo",
            ),
        ),
        migrations.AddField(
            model_name="campaignrun",
            name="target_wallet_platforms",
            field=models.CharField(
                choices=[
                    ("apple", "Apple Wallet"),
                    ("google", "Google Wallet"),
                    ("both", "Ambos"),
                    ("none", "Ninguno"),
                ],
                default="both",
                max_length=20,
                verbose_name="Plataformas de wallet objetivo",
            ),
        ),
    ]
