# Generated by Django 5.2.15 on 2026-10-07 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0010_campaignrun_loyallia_ca_tenant__c47733_idx"),
        ("tenants", "0013_alter_tenant_slug"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="campaignrun",
            name="whatsapp_session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="campaign_runs",
                to="notifications.whatsappsession",
                verbose_name="Sesión WhatsApp",
            ),
        ),
        migrations.AddField(
            model_name="whatsappsession",
            name="consent_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Consentimiento"
            ),
        ),
        migrations.AddField(
            model_name="whatsappsession",
            name="consent_by",
            field=models.UUIDField(
                blank=True, null=True, verbose_name="Consentimiento por"
            ),
        ),
        migrations.AddField(
            model_name="whatsappsession",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Activo"),
        ),
        migrations.AddField(
            model_name="whatsappsession",
            name="label",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional name, e.g. 'Ventas', 'Soporte'.",
                max_length=50,
                verbose_name="Etiqueta",
            ),
        ),
        migrations.AddField(
            model_name="whatsappsession",
            name="linked_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="whatsapp_sessions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Vinculado por",
            ),
        ),
        migrations.AlterField(
            model_name="whatsappsession",
            name="daily_limit_override",
            field=models.PositiveIntegerField(
                default=0,
                help_text="SuperAdmin override for THIS number. 0=auto. Max safe value: 200.",
                verbose_name="Override límite diario",
            ),
        ),
        migrations.AlterField(
            model_name="whatsappsession",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="whatsapp_sessions",
                to="tenants.tenant",
                verbose_name="Negocio",
            ),
        ),
        migrations.AddIndex(
            model_name="whatsappsession",
            index=models.Index(
                fields=["tenant", "is_connected"], name="loyallia_wh_tenant__809b4f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="whatsappsession",
            index=models.Index(
                fields=["tenant", "is_active"], name="loyallia_wh_tenant__02f24a_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="whatsappsession",
            constraint=models.UniqueConstraint(
                condition=models.Q(("phone_number", ""), _negated=True),
                fields=("tenant", "phone_number"),
                name="uniq_whatsapp_session_tenant_phone",
            ),
        ),
    ]
