# Generated by Django 5.0.6 on 2026-04-22 15:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_card_barcode_type'),
        ('customers', '0002_alter_customerpass_qr_code'),
        ('tenants', '0004_tenant_default_language'),
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['tenant', 'customer', 'card'], name='idx_enroll_tnt_cust_card'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['tenant', 'customer_pass', 'created_at'], name='idx_txn_tenant_pass_date'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_type', 'created_at'], name='idx_txn_type_date'),
        ),
    ]
