# Generated by Django 5.0.6 on 2026-05-01 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0005_remove_customerpass_idx_pass_card_active_and_more"),
        ("transactions", "0003_transaction_idx_txn_tenant_type_date"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="transaction",
            name="idx_txn_tenant_type_date",
        ),
        migrations.AlterField(
            model_name="transaction",
            name="customer_pass",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="customers.customerpass",
                verbose_name="Pase del cliente",
            ),
        ),
    ]
