# Generated by Django 5.2.14 on 2026-06-03 20:35

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0010_alter_card_background_color_alter_card_barcode_type_and_more"),
        ("customers", "0010_alter_applepassregistration_customer_pass_and_more"),
        ("tenants", "0011_alter_location_address_alter_location_city_and_more"),
        ("transactions", "0006_transaction_denial_reason_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrollment",
            name="card",
            field=models.ForeignKey(
                blank=True,
                help_text="The loyalty program associated with this record.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="enrollments",
                to="cards.card",
                verbose_name="Programa",
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                help_text="The customer associated with this record.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="enrollments",
                to="customers.customer",
                verbose_name="Cliente",
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="enrolled_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Timestamp for enrolled."
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="enrollment_method",
            field=models.CharField(
                choices=[
                    ("qr_scan", "Escaneo QR"),
                    ("direct_link", "Enlace directo"),
                    ("referral", "Referido"),
                    ("manual", "Manual"),
                ],
                default="qr_scan",
                help_text="How the customer enrolled.",
                max_length=20,
                verbose_name="Método de inscripción",
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Unique identifier for this record.",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="ip_address",
            field=models.GenericIPAddressField(
                blank=True,
                help_text="IP address of the client.",
                null=True,
                verbose_name="Dirección IP",
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="location",
            field=models.ForeignKey(
                blank=True,
                help_text="Physical location where the action took place.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="enrollments",
                to="tenants.location",
                verbose_name="Ubicación",
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="referral_code_used",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Referral code used during enrollment.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="tenant",
            field=models.ForeignKey(
                help_text="The business this record belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to="tenants.tenant",
                verbose_name="Negocio",
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="user_agent",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Client user agent string.",
                verbose_name="User Agent",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Monetary amount.",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Monto",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Timestamp for created."
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="customer_pass",
            field=models.ForeignKey(
                blank=True,
                help_text="The customer loyalty pass.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="customers.customerpass",
                verbose_name="Pase del cliente",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="denial_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "N/A"),
                    ("usage_limit_exceeded", "Límite de usos excedido"),
                    ("time_window_invalid", "Fuera de período válido"),
                    ("location_invalid", "Ubicación no autorizada"),
                    ("min_purchase_not_met", "Compra mínima no alcanzada"),
                    ("cooldown_active", "En período de enfriamiento"),
                    ("insufficient_balance", "Saldo insuficiente"),
                    ("reward_not_ready", "Recompensa no disponible"),
                    ("staff_role_denied", "Rol de personal no autorizado"),
                    ("card_not_published", "Programa no publicado"),
                    ("pass_expired", "Pase expirado"),
                    ("pass_inactive", "Pase inactivo"),
                ],
                default="",
                help_text="Reason why the transaction was denied.",
                max_length=50,
                verbose_name="Motivo de denegación",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Unique identifier for this record.",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="idempotency_key",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Key for ensuring exactly-once semantics.",
                max_length=64,
                verbose_name="Clave de idempotencia",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="is_remote",
            field=models.BooleanField(
                default=False,
                help_text="Whether this transaction was performed remotely.",
                verbose_name="Transacción remota",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="location",
            field=models.ForeignKey(
                blank=True,
                help_text="Physical location where the action took place.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="tenants.location",
                verbose_name="Ubicación",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="notes",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Additional notes or comments.",
                verbose_name="Notas",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="quantity",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Quantity or count.",
                null=True,
                verbose_name="Cantidad",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="rules_evaluated",
            field=models.JSONField(
                default=list,
                help_text="Rules that were evaluated for this transaction.",
                verbose_name="Reglas evaluadas",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="staff",
            field=models.ForeignKey(
                blank=True,
                help_text="The staff member who performed this action.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Personal",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="tenant",
            field=models.ForeignKey(
                help_text="The business this record belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="tenants.tenant",
                verbose_name="Negocio",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_data",
            field=models.JSONField(
                default=dict,
                help_text="Transaction metadata stored as JSON.",
                verbose_name="Datos de transacción",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("stamp_earned", "Sello ganado"),
                    ("stamp_redeemed", "Sello canjeado"),
                    ("cashback_earned", "Cashback ganado"),
                    ("cashback_redeemed", "Cashback canjeado"),
                    ("coupon_redeemed", "Cupón canjeado"),
                    ("gift_redeemed", "Regalo canjeado"),
                    ("membership_validated", "Membresía validada"),
                    ("corporate_validated", "Corporativo validado"),
                    ("referral_reward", "Recompensa por referido"),
                    ("multipass_used", "Multipase usado"),
                    ("remote_reward", "Recompensa remota"),
                    ("denied", "Denegado"),
                ],
                help_text="Transaction type.",
                max_length=30,
                verbose_name="Tipo de transacción",
            ),
        ),
    ]
