# Generated by Django 5.2.14 on 2026-06-03 22:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0012_card_loyallia_ca_tenant__90dc30_idx_and_more"),
        ("customers", "0014_customerpass_loyallia_cu_tenant__a39d50_idx_and_more"),
        ("tenants", "0011_alter_location_address_alter_location_city_and_more"),
        ("transactions", "0008_transaction_created_by_transaction_updated_by_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(
                fields=["customer"], name="loyallia_en_custome_e849dd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["tenant", "idempotency_key"],
                name="loyallia_tr_tenant__a3cc0f_idx",
            ),
        ),
    ]
