# Generated by Django 5.0.6 on 2026-06-03 23:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIQueryLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True),
                ),
                (
                    "endpoint",
                    models.CharField(
                        choices=[
                            ("generate-template", "Generate Template"),
                            ("suggest-colors", "Suggest Colors"),
                            ("critique-design", "Critique Design"),
                            ("suggest-stamp-icons", "Suggest Stamp Icons"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "prompt_tokens",
                    models.PositiveIntegerField(default=0),
                ),
                (
                    "completion_tokens",
                    models.PositiveIntegerField(default=0),
                ),
                (
                    "total_tokens",
                    models.PositiveIntegerField(default=0),
                ),
                (
                    "cost_usd",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        max_digits=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("error", "Error"),
                        ],
                        default="success",
                        max_length=16,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, default=""),
                ),
                (
                    "request_data",
                    models.JSONField(default=dict),
                ),
                (
                    "response_data",
                    models.JSONField(default=dict),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_query_logs",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "ai_query_log",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="aiquerylog",
            index=models.Index(
                fields=["tenant", "endpoint", "created_at"],
                name="ai_query_log_tenant_endpoint_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="aiquerylog",
            index=models.Index(
                fields=["tenant", "created_at"],
                name="ai_query_log_tenant_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="aiquerylog",
            index=models.Index(
                fields=["status", "created_at"],
                name="ai_query_log_status_created_idx",
            ),
        ),
    ]
