# Generated by Django 5.2.15 on 2026-06-04 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
        ('tenants', '0012_platformsetting_created_at'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='aiquerylog',
            new_name='ai_query_lo_tenant__4213bf_idx',
            old_name='ai_query_log_tenant_endpoint_idx',
        ),
        migrations.RenameIndex(
            model_name='aiquerylog',
            new_name='ai_query_lo_tenant__67854a_idx',
            old_name='ai_query_log_tenant_created_idx',
        ),
        migrations.RenameIndex(
            model_name='aiquerylog',
            new_name='ai_query_lo_status_c163ab_idx',
            old_name='ai_query_log_status_created_idx',
        ),
        migrations.AlterField(
            model_name='aiquerylog',
            name='cost_usd',
            field=models.DecimalField(decimal_places=6, default=0, help_text='Estimated cost in USD for this query.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='aiquerylog',
            name='endpoint',
            field=models.CharField(choices=[('generate-template', 'Generate Template'), ('suggest-colors', 'Suggest Colors'), ('critique-design', 'Critique Design'), ('suggest-stamp-icons', 'Suggest Stamp Icons')], help_text='AI endpoint that was called.', max_length=32),
        ),
        migrations.AlterField(
            model_name='aiquerylog',
            name='request_data',
            field=models.JSONField(default=dict, help_text='Snapshot of request parameters (description, card_type, etc.).'),
        ),
        migrations.AlterField(
            model_name='aiquerylog',
            name='response_data',
            field=models.JSONField(default=dict, help_text='Snapshot of AI response data.'),
        ),
        migrations.AlterField(
            model_name='aiquerylog',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant that initiated the AI request.', on_delete=django.db.models.deletion.CASCADE, related_name='ai_query_logs', to='tenants.tenant'),
        ),
    ]
