# Generated by Django 5.2.15 on 2026-06-08 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ai",
            "0002_rename_ai_query_log_tenant_endpoint_idx_ai_query_lo_tenant__4213bf_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="aiquerylog",
            name="endpoint",
            field=models.CharField(
                choices=[
                    ("generate-template", "Generate Template"),
                    ("suggest-colors", "Suggest Colors"),
                    ("critique-design", "Critique Design"),
                    ("suggest-stamp-icons", "Suggest Stamp Icons"),
                    ("suggest-layout", "Suggest Layout"),
                ],
                help_text="AI endpoint that was called.",
                max_length=32,
            ),
        ),
    ]
