# Generated by Django 5.0.6 on 2026-04-22 03:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_id', models.UUIDField(db_index=True, verbose_name='ID del actor')),
                ('actor_email', models.CharField(max_length=255, verbose_name='Email del actor')),
                ('actor_role', models.CharField(max_length=20, verbose_name='Rol del actor')),
                ('action', models.CharField(choices=[('CREATE', 'Crear'), ('READ', 'Leer'), ('UPDATE', 'Actualizar'), ('DELETE', 'Eliminar'), ('EXPORT', 'Exportar'), ('IMPORT', 'Importar'), ('IMPERSONATE', 'Suplantación'), ('LOGIN', 'Inicio de sesión'), ('LOGOUT', 'Cierre de sesión'), ('API_ACCESS', 'Acceso API')], max_length=20, verbose_name='Acción')),
                ('resource_type', models.CharField(max_length=50, verbose_name='Tipo de recurso')),
                ('resource_id', models.CharField(blank=True, default='', max_length=100, verbose_name='ID del recurso')),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True, verbose_name='ID del negocio')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, default='', verbose_name='User Agent')),
                ('justification', models.TextField(blank=True, default='', help_text='Required for impersonation actions', verbose_name='Justificación')),
                ('details', models.JSONField(default=dict, verbose_name='Detalles')),
                ('status', models.CharField(choices=[('success', 'Exitoso'), ('denied', 'Denegado'), ('error', 'Error')], default='success', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha')),
            ],
            options={
                'verbose_name': 'Registro de auditoría',
                'verbose_name_plural': 'Registros de auditoría',
                'db_table': 'loyallia_audit_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['actor_id', 'created_at'], name='loyallia_au_actor_i_b75e5a_idx'), models.Index(fields=['resource_type', 'created_at'], name='loyallia_au_resourc_0e84be_idx'), models.Index(fields=['tenant_id', 'created_at'], name='loyallia_au_tenant__3d873d_idx'), models.Index(fields=['action', 'created_at'], name='loyallia_au_action_3eec23_idx')],
            },
        ),
    ]
