# Generated by Django 5.2.14 on 2026-06-03 20:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0003_alter_auditlog_action_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("CREATE", "Crear"),
                    ("READ", "Leer"),
                    ("UPDATE", "Actualizar"),
                    ("DELETE", "Eliminar"),
                    ("EXPORT", "Exportar"),
                    ("IMPORT", "Importar"),
                    ("IMPERSONATE", "Suplantación"),
                    ("LOGIN", "Inicio de sesión"),
                    ("LOGOUT", "Cierre de sesión"),
                    ("API_ACCESS", "Acceso API"),
                    ("FACTORY_RESET", "Restauración de fábrica"),
                    ("SEED_DEMO", "Carga de datos demo"),
                    ("BACKUP", "Respaldo"),
                    ("RESTORE", "Restauración"),
                ],
                help_text="Action performed.",
                max_length=20,
                verbose_name="Acción",
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="actor_email",
            field=models.CharField(
                help_text="Email of the actor who performed the action.",
                max_length=255,
                verbose_name="Email del actor",
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="actor_id",
            field=models.UUIDField(
                db_index=True,
                help_text="ID of the actor who performed the action.",
                verbose_name="ID del actor",
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="actor_role",
            field=models.CharField(
                help_text="Role of the actor.",
                max_length=20,
                verbose_name="Rol del actor",
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="Timestamp for created.",
                verbose_name="Fecha",
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="details",
            field=models.JSONField(
                default=dict,
                help_text="Additional details or context.",
                verbose_name="Detalles",
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Unique identifier for this record.",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="ip_address",
            field=models.GenericIPAddressField(
                blank=True,
                help_text="IP address of the client.",
                null=True,
                verbose_name="Dirección IP",
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="resource_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Identifier of the affected resource.",
                max_length=100,
                verbose_name="ID del recurso",
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="resource_type",
            field=models.CharField(
                help_text="Type of resource affected.",
                max_length=50,
                verbose_name="Tipo de recurso",
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="status",
            field=models.CharField(
                choices=[
                    ("success", "Exitoso"),
                    ("denied", "Denegado"),
                    ("error", "Error"),
                ],
                default="success",
                help_text="Current status of this record.",
                max_length=20,
                verbose_name="Estado",
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="tenant_id",
            field=models.UUIDField(
                blank=True,
                db_index=True,
                help_text="Identifier of the business.",
                null=True,
                verbose_name="ID del negocio",
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="user_agent",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Client user agent string.",
                verbose_name="User Agent",
            ),
        ),
    ]
