/**
 * System template registry for the Wallet Pass Studio.
 *
 * 20 built-in templates covering a wide range of industries and card types.
 */

import type { WalletTemplate } from '@/components/wallet/types/templates';
import { defaultBackContentDefaults } from '@/components/wallet/types/back-content';

const now = new Date().toISOString();

export const SYSTEM_TEMPLATES: WalletTemplate[] = [
  /* ── 1. Café Clásico ─────────────────────────────────────────────── */
  {
    id: 'cafe-classico-sellos',
    name: 'Café Clásico',
    description: 'Sellos: ☕×10',
    type: 'system',
    cardType: 'stamp',
    industry: 'food',
    colors: {
      background: '#6B4226',
      foreground: '#FFFFFF',
      label: '#F5DEB3',
      accent: '#D2691E',
    },
    cardTypeConfig: {
      cardType: 'stamp',
      stampsRequired: 10,
      rewardDescription: 'Café gratis',
      stampType: 'visit',
      consumptionPerStamp: 1,
      stampExpiry: 'unlimited',
      stampsAtIssue: 0,
      dailyStampLimit: 1,
      birthdayStamps: 1,
      stampShape: 'circle',
      stampIcon: 'coffee',
      stampFilledIcon: 'coffee-filled',
      stampColor: '#D2691E',
      stampGridLayout: '5x2',
    },
    barcode: { format: 'QR_CODE', message: '', messageEncoding: 'iso-8859-1' },
    backContent: defaultBackContentDefaults.stamp,
    apple: {
      passStyle: 'storeCard',
      description: 'Tarjeta de sellos de café',
      organizationName: 'Café Clásico',
    },
    google: {
      passType: 'LoyaltyClass',
      programName: 'Café Clásico Rewards',
      hexBackgroundColor: '#6B4226',
    },
    tags: ['café', 'food', 'stamp'],
    createdAt: now,
    updatedAt: now,
  },

  /* ── 2. Café Cashback ────────────────────────────────────────────── */
  {
    id: 'cafe-cashback',
    name: 'Café Cashback',
    description: '5% de reembolso en cada compra',
    type: 'system',
    cardType: 'cashback',
    industry: 'food',
    colors: {
      background: '#3E2723',
      foreground: '#FFFFFF',
      label: '#D7CCC8',
      accent: '#FF7043',
    },
    cardTypeConfig: {
      cardType: 'cashback',
      cashbackPercentage: 5,
      minimumPurchase: 50,
      creditExpiryDays: 90,
      tierName: 'Amigo del Café',
      coinIcon: 'coin',
      tierBadge: 'badge-bronze',
      progressRingColor: '#FF7043',
    },
    barcode: { format: 'QR_CODE', message: '', messageEncoding: 'iso-8859-1' },
    backContent: defaultBackContentDefaults.cashback,
    apple: {
      passStyle: 'storeCard',
      description: 'Cashback en café',
      organizationName: 'Café Cashback',
    },
    google: {
      passType: 'LoyaltyClass',
      programName: 'Café Cashback',
      hexBackgroundColor: '#3E2723',
    },
    tags: ['café', 'food', 'cashback'],
    createdAt: now,
    updatedAt: now,
  },

  /* ── 3. Retail Moderno ───────────────────────────────────────────── */
  {
    id: 'retail-moderno',
    name: 'Retail Moderno',
    description: 'Descuentos por niveles de compra',
    type: 'system',
    cardType: 'discount',
    industry: 'retail',
    colors: {
      background: '#FFFFFF',
      foreground: '#1A1A1A',
      label: '#666666',
      accent: '#E53935',
    },
    cardTypeConfig: {
      cardType: 'discount',
      tiers: [
        { tierName: 'Bronce', threshold: 0, discountPercentage: 5 },
        { tierName: 'Plata', threshold: 500, discountPercentage: 10 },
        { tierName: 'Oro', threshold: 1500, discountPercentage: 15 },
      ],
      tierBadgeIcons: ['badge-bronze', 'badge-silver', 'badge-gold'],
      progressBarColor: '#E53935',
      percentageDisplayStyle: 'badge',
      discountBannerText: 'Más compras, más ahorro',
    },
    barcode: { format: 'QR_CODE', message: '', messageEncoding: 'iso-8859-1' },
    backContent: defaultBackContentDefaults.discount,
    apple: {
      passStyle: 'storeCard',
      description: 'Descuentos por niveles',
      organizationName: 'Retail Moderno',
    },
    google: {
      passType: 'LoyaltyClass',
      programName: 'Retail Moderno VIP',
      hexBackgroundColor: '#FFFFFF',
    },
    tags: ['retail', 'discount'],
    createdAt: now,
    updatedAt: now,
  },

  /* ── 4. Gym Pro ──────────────────────────────────────────────────── */
  {
    id: 'gym-pro',
    name: 'Gym Pro',
    description: 'Membresía VIP Oro',
    type: 'system',
    cardType: 'vip_membership',
    industry: 'health',
    colors: {
      background: '#1A1A2E',
      foreground: '#FFFFFF',
      label: '#E94560',
      accent: '#E94560',
    },
    cardTypeConfig: {
      cardType: 'vip_membership',
      membershipName: 'Gym Pro VIP',
      monthlyFee: 49.99,
      annualFee: 499.99,
      validityPeriod: 'monthly',
      perks: ['Acceso ilimitado', 'Clases grupales', 'Sauna', 'Nutricionista'],
      crownIcon: 'crown-gold',
      memberBadgeStyle: 'gold',
      benefitsListIcons: ['dumbbell', 'users', 'flame', 'apple'],
    },
    barcode: { format: 'QR_CODE', message: '', messageEncoding: 'iso-8859-1' },
    backContent: defaultBackContentDefaults.vip_membership,
    apple: {
      passStyle: 'generic',
      description: 'Membresía Gym Pro',
      organizationName: 'Gym Pro',
    },
    google: {
      passType: 'LoyaltyClass',
      programName: 'Gym Pro Membership',
      hexBackgroundColor: '#1A1A2E',
    },
    tags: ['gym', 'health', 'vip'],
    createdAt: now,
    updatedAt: now,
  },

  /* ── 5. Salón de Belleza ─────────────────────────────────────────── */
  {
    id: 'salon-belleza',
    name: 'Salón de Belleza',
    description: 'Sellos: ✂️×8',
    type: 'system',
    cardType: 'stamp',
    industry: 'services',
    colors: {
      background: '#880E4F',
      foreground: '#FFFFFF',
      label: '#F8BBD0',
      accent: '#FF4081',
    },
    cardTypeConfig: {
      cardType: 'stamp',
      stampsRequired: 8,
      rewardDescription: 'Corte gratis',
      stampType: 'visit',
      consumptionPerStamp: 1,
      stampExpiry: 'unlimited',
      stampsAtIssue: 0,
      dailyStampLimit: 1,
      birthdayStamps: 1,
      stampShape: 'heart',
      stampIcon: 'scissors',
      stampFilledIcon: 'scissors-filled',
      stampColor: '#FF4081',
      stampGridLayout: '4x4',
    },
    barcode: { format: 'QR_CODE', message: '', messageEncoding: 'iso-8859-1' },
    backContent: defaultBackContentDefaults.stamp,
    apple: {
      passStyle: 'storeCard',
      description: 'Tarjeta de sellos salón',
      organizationName: 'Salón de Belleza',
    },
    google: {
      passType: 'LoyaltyClass',
      programName: 'Salón Belleza Rewards',
      hexBackgroundColor: '#880E4F',
    },
    tags: ['salón', 'services', 'stamp'],
    createdAt: now,
    updatedAt: now,
  },

  /* ── 6. Hotel Lujo ───────────────────────────────────────────────── */
  {
    id: 'hotel-lujo',
    name: 'Hotel Lujo',
    description: 'Membresía Club Ejecutivo',
    type: 'system',
    cardType: 'vip_membership',
    industry: 'services',
    colors: {
      background: '#1A1A1A',
      foreground: '#FFFFFF',
      label: '#B0B0B0',
      accent: '#C0A062',
    },
    cardTypeConfig: {
      cardType: 'vip_membership',
      membershipName: 'Club Ejecutivo',
      monthlyFee: 99,
      annualFee: 999,
      validityPeriod: 'annual',
      perks: ['Upgrade habitación', 'Desayuno incluido', 'Late checkout', 'Spa gratuito'],
      crownIcon: 'crown-platinum',
      memberBadgeStyle: 'platinum',
      benefitsListIcons: ['bed', 'coffee', 'clock', 'spa'],
    },
    barcode: { format: 'QR_CODE', message: '', messageEncoding: 'iso-8859-1' },
    backContent: defaultBackContentDefaults.vip_membership,
    apple: {
      passStyle: 'generic',
      description: 'Membresía Hotel Lujo',
      organizationName: 'Hotel Lujo',
    },
    google: {
      passType: 'LoyaltyClass',
      programName: 'Hotel Lujo Club',
      hexBackgroundColor: '#1A1A1A',
    },
    tags: ['hotel', 'services', 'vip'],
    createdAt: now,
    updatedAt: now,
  },

  /* ── 7. Food Truck Rápido ────────────────────────────────────────── */
  {
    id: 'foodtruck-rapido',
    name: 'Food Truck Rápido',
    description: 'Cupón: 2×1 en tacos',
    type: 'system',
    cardType: 'coupon',
    industry: 'food',
    colors: {
      background: '#FFF3E0',
      foreground: '#E65100',
      label: '#F57C00',
      accent: '#FF9800',
    },
    cardTypeConfig: {
      cardType: 'coupon',
      discountType: 'percentage',
      discountValue: 50,
      usageLimitPerCustomer: 2,
      couponDescription: '2×1 en todos los tacos',
      specialPromotionText: 'Válido de lunes a jueves',
      couponExpiry: 30,
      couponStartDate: undefined,
      couponEndDate: undefined,
      pushMessage: '¡Nuevos tacos esta semana!',
      cutLineStyle: 'dashed',
      discountBadgeStyle: 'banner',
      offerTag: '2×1',
    },
    barcode: { format: 'QR_CODE', message: '', messageEncoding: 'iso-8859-1' },
    backContent: defaultBackContentDefaults.coupon,
    apple: {
      passStyle: 'coupon',
      description: 'Cupón Food Truck',
      organizationName: 'Food Truck Rápido',
    },
    google: {
      passType: 'OfferClass',
      programName: 'Food Truck Ofertas',
      hexBackgroundColor: '#FFF3E0',
    },
    tags: ['food truck', 'food', 'coupon'],
    createdAt: now,
    updatedAt: now,
  },

  /* ── 8. Librería Sabiduría ───────────────────────────────────────── */
  {
    id: 'libreria-sabiduria',
    name: 'Librería Sabiduría',
    description: 'Sellos: 📚×12',
    type: 'system',
    cardType: 'stamp',
    industry: 'retail',
    colors: {
      background: '#1B5E20',
      foreground: '#FFFFFF',
      label: '#C8E6C9',
      accent: '#69F0AE',
    },
    cardTypeConfig: {
      cardType: 'stamp',
      stampsRequired: 12,
      rewardDescription: 'Libro gratuito',
      stampType: 'consumption',
      consumptionPerStamp: 200,
      stampExpiry: 'unlimited',
      stampsAtIssue: 0,
      dailyStampLimit: 5,
      birthdayStamps: 2,
      stampShape: 'diamond',
      stampIcon: 'book',
      stampFilledIcon: 'book-filled',
      stampColor: '#69F0AE',
      stampGridLayout: '6x2',
    },
    barcode: { format: 'QR_CODE', message: '', messageEncoding: 'iso-8859-1' },
    backContent: defaultBackContentDefaults.stamp,
    apple: {
      passStyle: 'storeCard',
      description: 'Tarjeta de sellos librería',
      organizationName: 'Librería Sabiduría',
    },
    google: {
      passType: 'LoyaltyClass',
      programName: 'Librería Sabiduría Rewards',
      hexBackgroundColor: '#1B5E20',
    },
    tags: ['bookstore', 'retail', 'stamp'],
    createdAt: now,
    updatedAt: now,
  },

  /* ── 9. Farmacia Salud ───────────────────────────────────────────── */
  {
    id: 'farmacia-salud',
    name: 'Farmacia Salud',
    description: 'Descuentos progresivos',
    type: 'system',
    cardType: 'discount',
    industry: 'health',
    colors: {
      background: '#E8F5E9',
      foreground: '#1B5E20',
      label: '#388E3C',
      accent: '#4CAF50',
    },
    cardTypeConfig: {
      cardType: 'discount',
      tiers: [
        { tierName: 'Cliente', threshold: 0, discountPercentage: 3 },
        { tierName: 'Frecuente', threshold: 300, discountPercentage: 7 },
        { tierName: 'VIP', threshold: 800, discountPercentage: 12 },
      ],
      tierBadgeIcons: ['badge-green', 'badge-teal', 'badge-emerald'],
      progressBarColor: '#4CAF50',
      percentageDisplayStyle: 'expanded',
      discountBannerText: 'Tu salud, tu ahorro',
    },
    barcode: { format: 'QR_CODE', message: '', messageEncoding: 'iso-8859-1' },
    backContent: defaultBackContentDefaults.discount,
    apple: {
      passStyle: 'storeCard',
      description: 'Descuentos Farmacia Salud',
      organizationName: 'Farmacia Salud',
    },
    google: {
      passType: 'LoyaltyClass',
      programName: 'Farmacia Salud VIP',
      hexBackgroundColor: '#E8F5E9',
    },
    tags: ['pharmacy', 'health', 'discount'],
    createdAt: now,
    updatedAt: now,
  },

  /* ── 10. Pet Shop Mascotas ───────────────────────────────────────── */
  {
    id: 'petshop-mascotas',
    name: 'Pet Shop Mascotas',
    description: 'Sellos: 🐾×10',
    type: 'system',
    cardType: 'stamp',
    industry: 'retail',
    colors: {
      background: '#F3E5F5',
      foreground: '#4A148C',
      label: '#7B1FA2',
      accent: '#9C27B0',
    },
    cardTypeConfig: {
      cardType: 'stamp',
      stampsRequired: 10,
      rewardDescription: 'Baño gratis',
      stampType: 'visit',
      consumptionPerStamp: 1,
      stampExpiry: 'unlimited',
      stampsAtIssue: 0,
      dailyStampLimit: 2,
      birthdayStamps: 1,
      stampShape: 'hexagon',
      stampIcon: 'paw',
      stampFilledIcon: 'paw-filled',
      stampColor: '#9C27B0',
      stampGridLayout: '5x2',
    },
    barcode: { format: 'QR_CODE', message: '', messageEncoding: 'iso-8859-1' },
    backContent: defaultBackContentDefaults.stamp,
    apple: {
      passStyle: 'storeCard',
      description: 'Tarjeta de sellos mascotas',
      organizationName: 'Pet Shop Mascotas',
    },
    google: {
      passType: 'LoyaltyClass',
      programName: 'Pet Shop Rewards',
      hexBackgroundColor: '#F3E5F5',
    },
    tags: ['pet shop', 'retail', 'stamp'],
    createdAt: now,
    updatedAt: now,
  },

  /* ── 11. Panadería Dulce ─────────────────────────────────────────── */
  {
    id: 'panaderia-dulce',
    name: 'Panadería Dulce',
    description: 'Sellos: 🥐×8',
    type: 'system',
    cardType: 'stamp',
    industry: 'food',
    colors: {
      background: '#FFF8E1',
      foreground: '#3E2723',
      label: '#8D6E63',
      accent: '#FF6F00',
    },
    cardTypeConfig: {
      cardType: 'stamp',
      stampsRequired: 8,
      rewardDescription: 'Docena de medialunas',
      stampType: 'consumption',
      consumptionPerStamp: 100,
      stampExpiry: 'unlimited',
      stampsAtIssue: 1,
      dailyStampLimit: 3,
      birthdayStamps: 2,
      stampShape: 'star',
      stampIcon: 'croissant',
      stampFilledIcon: 'croissant-filled',
      stampColor: '#FF6F00',
      stampGridLayout: '4x4',
    },
    barcode: { format: 'QR_CODE', message: '', messageEncoding: 'iso-8859-1' },
    backContent: defaultBackContentDefaults.stamp,
    apple: {
      passStyle: 'storeCard',
      description: 'Tarjeta de sellos panadería',
      organizationName: 'Panadería Dulce',
    },
    google: {
      passType: 'LoyaltyClass',
      programName: 'Panadería Dulce Rewards',
      hexBackgroundColor: '#FFF8E1',
    },
    tags: ['bakery', 'food', 'stamp'],
    createdAt: now,
    updatedAt: now,
  },

  /* ── 12. Restaurante Gourmet ─────────────────────────────────────── */
  {
    id: 'restaurante-gourmet',
    name: 'Restaurante Gourmet',
    description: 'Cashback 8% en cenas',
    type: 'system',
    cardType: 'cashback',
    industry: 'food',
    colors: {
      background: '#37474F',
      foreground: '#FFFFFF',
      label: '#B0BEC5',
      accent: '#26A69A',
    },
    cardTypeConfig: {
      cardType: 'cashback',
      cashbackPercentage: 8,
      minimumPurchase: 100,
      creditExpiryDays: 180,
      tierName: 'Gourmet',
      coinIcon: 'coin-silver',
      tierBadge: 'badge-silver',
      progressRingColor: '#26A69A',
    },
    barcode: { format: 'QR_CODE', message: '', messageEncoding: 'iso-8859-1' },
    backContent: defaultBackContentDefaults.cashback,
    apple: {
      passStyle: 'storeCard',
      description: 'Cashback Restaurante Gourmet',
      organizationName: 'Restaurante Gourmet',
    },
    google: {
      passType: 'LoyaltyClass',
      programName: 'Gourmet Rewards',
      hexBackgroundColor: '#37474F',
    },
    tags: ['restaurant', 'food', 'cashback'],
    createdAt: now,
    updatedAt: now,
  },

  /* ── 13. Barbería Clásica ────────────────────────────────────────── */
  {
    id: 'barberia-clasica',
    name: 'Barbería Clásica',
    description: 'Multi-pase: 5 cortes',
    type: 'system',
    cardType: 'multipass',
    industry: 'services',
    colors: {
      background: '#0D1117',
      foreground: '#C9D1D9',
      label: '#8B949E',
      accent: '#58A6FF',
    },
    cardTypeConfig: {
      cardType: 'multipass',
      bundleSize: 5,
      bundlePrice: 200,
      passTypeLabel: 'Corte + Barba',
      ticketGraphic: 'ticket-barber',
      punchIcon: 'check',
      bundleBadgeStyle: 'visual',
      indicatorStyle: 'visual',
    },
    barcode: { format: 'QR_CODE', message: '', messageEncoding: 'iso-8859-1' },
    backContent: defaultBackContentDefaults.multipass,
    apple: {
      passStyle: 'eventTicket',
      description: 'Multi-pase Barbería',
      organizationName: 'Barbería Clásica',
    },
    google: {
      passType: 'GenericClass',
      programName: 'Barbería Clásica Pass',
      hexBackgroundColor: '#0D1117',
    },
    tags: ['barber', 'services', 'multipass'],
    createdAt: now,
    updatedAt: now,
  },

  /* ── 14. Spa Relax ───────────────────────────────────────────────── */
  {
    id: 'spa-relax',
    name: 'Spa Relax',
    description: 'Certificado de regalo',
    type: 'system',
    cardType: 'gift_certificate',
    industry: 'health',
    colors: {
      background: '#EDE7F6',
      foreground: '#311B92',
      label: '#5E35B1',
      accent: '#7C4DFF',
    },
    cardTypeConfig: {
      cardType: 'gift_certificate',
      denominations: [50, 100, 200, 500],
      expiryDays: 365,
      boxGraphic: 'gift-box-lavender',
      ribbonColor: '#7C4DFF',
      occasion: 'Cumpleaños',
      denominationBadge: 'gift-badge',
    },
    barcode: { format: 'QR_CODE', message: '', messageEncoding: 'iso-8859-1' },
    backContent: defaultBackContentDefaults.gift_certificate,
    apple: {
      passStyle: 'storeCard',
      description: 'Certificado Spa Relax',
      organizationName: 'Spa Relax',
    },
    google: {
      passType: 'GiftCardClass',
      programName: 'Spa Relax Gift',
      hexBackgroundColor: '#EDE7F6',
    },
    tags: ['spa', 'health', 'gift'],
    createdAt: now,
    updatedAt: now,
  },

  /* ── 15. Cine Estrella ───────────────────────────────────────────── */
  {
    id: 'cine-estrella',
    name: 'Cine Estrella',
    description: 'Multi-pase: 10 entradas',
    type: 'system',
    cardType: 'multipass',
    industry: 'entertainment',
    colors: {
      background: '#311B92',
      foreground: '#FFFFFF',
      label: '#D1C4E9',
      accent: '#E040FB',
    },
    cardTypeConfig: {
      cardType: 'multipass',
      bundleSize: 10,
      bundlePrice: 350,
      passTypeLabel: 'Entrada General',
      ticketGraphic: 'ticket-cinema',
      punchIcon: 'popcorn',
      bundleBadgeStyle: 'numeric',
      indicatorStyle: 'numeric',
    },
    barcode: { format: 'QR_CODE', message: '', messageEncoding: 'iso-8859-1' },
    backContent: defaultBackContentDefaults.multipass,
    apple: {
      passStyle: 'eventTicket',
      description: 'Multi-pase Cine Estrella',
      organizationName: 'Cine Estrella',
    },
    google: {
      passType: 'GenericClass',
      programName: 'Cine Estrella Pass',
      hexBackgroundColor: '#311B92',
    },
    tags: ['cinema', 'entertainment', 'multipass'],
    createdAt: now,
    updatedAt: now,
  },

  /* ── 16. Parking Ciudad ──────────────────────────────────────────── */
  {
    id: 'parking-ciudad',
    name: 'Parking Ciudad',
    description: 'Multi-pase: 20 usos',
    type: 'system',
    cardType: 'multipass',
    industry: 'transport',
    colors: {
      background: '#01579B',
      foreground: '#FFFFFF',
      label: '#B3E5FC',
      accent: '#03A9F4',
    },
    cardTypeConfig: {
      cardType: 'multipass',
      bundleSize: 20,
      bundlePrice: 400,
      passTypeLabel: 'Estacionamiento',
      ticketGraphic: 'ticket-parking',
      punchIcon: 'car',
      bundleBadgeStyle: 'minimal',
      indicatorStyle: 'minimal',
    },
    barcode: { format: 'QR_CODE', message: '', messageEncoding: 'iso-8859-1' },
    backContent: defaultBackContentDefaults.multipass,
    apple: {
      passStyle: 'eventTicket',
      description: 'Multi-pase Parking',
      organizationName: 'Parking Ciudad',
    },
    google: {
      passType: 'GenericClass',
      programName: 'Parking Ciudad Pass',
      hexBackgroundColor: '#01579B',
    },
    tags: ['parking', 'transport', 'multipass'],
    createdAt: now,
    updatedAt: now,
  },

  /* ── 17. Lavandería Fresh ────────────────────────────────────────── */
  {
    id: 'lavanderia-fresh',
    name: 'Lavandería Fresh',
    description: 'Sellos: 👕×10',
    type: 'system',
    cardType: 'stamp',
    industry: 'services',
    colors: {
      background: '#E0F7FA',
      foreground: '#006064',
      label: '#00838F',
      accent: '#00BCD4',
    },
    cardTypeConfig: {
      cardType: 'stamp',
      stampsRequired: 10,
      rewardDescription: 'Lavado gratis',
      stampType: 'consumption',
      consumptionPerStamp: 50,
      stampExpiry: 'unlimited',
      stampsAtIssue: 0,
      dailyStampLimit: 5,
      birthdayStamps: 1,
      stampShape: 'square',
      stampIcon: 'shirt',
      stampFilledIcon: 'shirt-filled',
      stampColor: '#00BCD4',
      stampGridLayout: '5x2',
    },
    barcode: { format: 'QR_CODE', message: '', messageEncoding: 'iso-8859-1' },
    backContent: defaultBackContentDefaults.stamp,
    apple: {
      passStyle: 'storeCard',
      description: 'Tarjeta de sellos lavandería',
      organizationName: 'Lavandería Fresh',
    },
    google: {
      passType: 'LoyaltyClass',
      programName: 'Lavandería Fresh Rewards',
      hexBackgroundColor: '#E0F7FA',
    },
    tags: ['laundry', 'services', 'stamp'],
    createdAt: now,
    updatedAt: now,
  },

  /* ── 18. Floristería Ramo ────────────────────────────────────────── */
  {
    id: 'floristeria-ramo',
    name: 'Floristería Ramo',
    description: 'Certificado de regalo floral',
    type: 'system',
    cardType: 'gift_certificate',
    industry: 'retail',
    colors: {
      background: '#FFF0F5',
      foreground: '#880E4F',
      label: '#C2185B',
      accent: '#F48FB1',
    },
    cardTypeConfig: {
      cardType: 'gift_certificate',
      denominations: [25, 50, 100],
      expiryDays: 180,
      boxGraphic: 'gift-box-rose',
      ribbonColor: '#F48FB1',
      occasion: 'Aniversario',
      denominationBadge: 'rose-badge',
    },
    barcode: { format: 'QR_CODE', message: '', messageEncoding: 'iso-8859-1' },
    backContent: defaultBackContentDefaults.gift_certificate,
    apple: {
      passStyle: 'storeCard',
      description: 'Certificado Floristería Ramo',
      organizationName: 'Floristería Ramo',
    },
    google: {
      passType: 'GiftCardClass',
      programName: 'Floristería Ramo Gift',
      hexBackgroundColor: '#FFF0F5',
    },
    tags: ['florist', 'retail', 'gift'],
    createdAt: now,
    updatedAt: now,
  },

  /* ── 19. Tech Store Digital ──────────────────────────────────────── */
  {
    id: 'techstore-digital',
    name: 'Tech Store Digital',
    description: 'Descuentos por niveles tech',
    type: 'system',
    cardType: 'discount',
    industry: 'technology',
    colors: {
      background: '#0D1117',
      foreground: '#C9D1D9',
      label: '#8B949E',
      accent: '#58A6FF',
    },
    cardTypeConfig: {
      cardType: 'discount',
      tiers: [
        { tierName: 'Explorer', threshold: 0, discountPercentage: 3 },
        { tierName: 'Pro', threshold: 1000, discountPercentage: 8 },
        { tierName: 'Elite', threshold: 3000, discountPercentage: 15 },
      ],
      tierBadgeIcons: ['badge-copper', 'badge-silver', 'badge-gold'],
      progressBarColor: '#58A6FF',
      percentageDisplayStyle: 'compact',
      discountBannerText: 'Tecnología al mejor precio',
    },
    barcode: { format: 'QR_CODE', message: '', messageEncoding: 'iso-8859-1' },
    backContent: defaultBackContentDefaults.discount,
    apple: {
      passStyle: 'storeCard',
      description: 'Descuentos Tech Store',
      organizationName: 'Tech Store Digital',
    },
    google: {
      passType: 'LoyaltyClass',
      programName: 'Tech Store VIP',
      hexBackgroundColor: '#0D1117',
    },
    tags: ['tech store', 'technology', 'discount'],
    createdAt: now,
    updatedAt: now,
  },

  /* ── 20. Supermercado Ahorro ─────────────────────────────────────── */
  {
    id: 'supermercado-ahorro',
    name: 'Supermercado Ahorro',
    description: 'Cashback 3% en todas las compras',
    type: 'system',
    cardType: 'cashback',
    industry: 'retail',
    colors: {
      background: '#2E8B57',
      foreground: '#FFFFFF',
      label: '#90EE90',
      accent: '#3CB371',
    },
    cardTypeConfig: {
      cardType: 'cashback',
      cashbackPercentage: 3,
      minimumPurchase: 0,
      creditExpiryDays: 90,
      tierName: 'Ahorrador',
      coinIcon: 'coin-gold',
      tierBadge: 'badge-green',
      progressRingColor: '#3CB371',
    },
    barcode: { format: 'QR_CODE', message: '', messageEncoding: 'iso-8859-1' },
    backContent: defaultBackContentDefaults.cashback,
    apple: {
      passStyle: 'storeCard',
      description: 'Cashback Supermercado Ahorro',
      organizationName: 'Supermercado Ahorro',
    },
    google: {
      passType: 'LoyaltyClass',
      programName: 'Supermercado Ahorro Rewards',
      hexBackgroundColor: '#2E8B57',
    },
    tags: ['supermarket', 'retail', 'cashback'],
    createdAt: now,
    updatedAt: now,
  },
];

/** Display categories for the template gallery filter pills. */
export const TEMPLATE_CATEGORIES = [
  { id: 'all', label: 'Todas', filter: () => true },
  { id: 'cafe', label: 'Café', filter: (t: WalletTemplate) => t.industry === 'food' || t.tags.includes('café') || t.tags.includes('bakery') },
  { id: 'retail', label: 'Retail', filter: (t: WalletTemplate) => t.industry === 'retail' || t.tags.includes('retail') },
  { id: 'gym', label: 'Gym', filter: (t: WalletTemplate) => t.tags.includes('gym') || t.industry === 'health' },
  { id: 'salon', label: 'Salón', filter: (t: WalletTemplate) => t.tags.includes('salón') || t.tags.includes('barber') || t.tags.includes('spa') || t.tags.includes('laundry') },
  { id: 'hotel', label: 'Hotel', filter: (t: WalletTemplate) => t.tags.includes('hotel') },
] as const;

/** Industry options for the dropdown filter. */
export const INDUSTRY_FILTER_OPTIONS = [
  { value: 'all', label: 'Todas las industrias' },
  { value: 'food', label: 'Alimentación y Bebidas' },
  { value: 'retail', label: 'Retail y Comercio' },
  { value: 'services', label: 'Servicios Profesionales' },
  { value: 'health', label: 'Salud y Bienestar' },
  { value: 'entertainment', label: 'Entretenimiento' },
  { value: 'transport', label: 'Transporte' },
  { value: 'technology', label: 'Tecnología' },
  { value: 'generic', label: 'Genérico' },
];

/** Card type options for the dropdown filter. */
export const CARD_TYPE_FILTER_OPTIONS = [
  { value: 'all', label: 'Todos los tipos' },
  { value: 'stamp', label: 'Tarjeta de Sellos' },
  { value: 'cashback', label: 'Cashback' },
  { value: 'coupon', label: 'Cupón' },
  { value: 'discount', label: 'Descuento por Niveles' },
  { value: 'vip_membership', label: 'Membresía VIP' },
  { value: 'gift_certificate', label: 'Tarjeta Regalo' },
  { value: 'multipass', label: 'Multi-Pase' },
];

/** Map card type to display label. */
export function getCardTypeLabel(cardType: WalletTemplate['cardType']): string {
  const option = CARD_TYPE_FILTER_OPTIONS.find((o) => o.value === cardType);
  return option?.label ?? cardType;
}

/** Map industry to display label. */
export function getIndustryLabel(industry: WalletTemplate['industry']): string {
  const option = INDUSTRY_FILTER_OPTIONS.find((o) => o.value === industry);
  return option?.label ?? industry;
}
