/**
 * System template definitions — batch 1 (templates 1–10).
 *
 * Extracted from registry.ts to keep each file under the 650-line project limit.
 */

import type { WalletTemplate } from '@/components/wallet/types/templates';
import { defaultBackContentDefaults } from '@/components/wallet/types/back-content';

const now = new Date().toISOString();

export const SYSTEM_TEMPLATES_01: WalletTemplate[] = [
  /* ── 1. Café Clásico ─────────────────────────────────────────────── */
  {
    id: 'cafe-classico-sellos',
    name: 'Café Clásico',
    description: 'Sellos: ☕×10',
    type: 'system',
    cardType: 'stamp',
    industry: 'food',
    colors: {
      background: '#6B4226',
      foreground: '#FFFFFF',
      label: '#F5DEB3',
      accent: '#D2691E',
    },
    cardTypeConfig: {
      cardType: 'stamp',
      stampsRequired: 10,
      rewardDescription: 'Café gratis',
      stampType: 'visit',
      consumptionPerStamp: 1,
      stampExpiry: 'unlimited',
      stampsAtIssue: 0,
      dailyStampLimit: 1,
      birthdayStamps: 1,
      stampShape: 'circle',
      stampIcon: 'coffee',
      stampFilledIcon: 'coffee-filled',
      stampColor: '#D2691E',
      stampGridLayout: '5x2',
    },
    barcode: { format: 'QR_CODE', message: '', messageEncoding: 'iso-8859-1' },
    backContent: defaultBackContentDefaults.stamp,
    apple: {
      passStyle: 'storeCard',
      description: 'Tarjeta de sellos de café',
      organizationName: 'Café Clásico',
    },
    google: {
      passType: 'LoyaltyClass',
      programName: 'Café Clásico Rewards',
      hexBackgroundColor: '#6B4226',
    },
    tags: ['café', 'food', 'stamp'],
    createdAt: now,
    updatedAt: now,
  },

  /* ── 2. Café Cashback ────────────────────────────────────────────── */
  {
    id: 'cafe-cashback',
    name: 'Café Cashback',
    description: '5% de reembolso en cada compra',
    type: 'system',
    cardType: 'cashback',
    industry: 'food',
    colors: {
      background: '#3E2723',
      foreground: '#FFFFFF',
      label: '#D7CCC8',
      accent: '#FF7043',
    },
    cardTypeConfig: {
      cardType: 'cashback',
      cashbackPercentage: 5,
      minimumPurchase: 50,
      creditExpiryDays: 90,
      creditExpiryType: 'defined_period' as const,
      tierName: 'Amigo del Café',
      coinIcon: 'coin',
      tierBadge: 'badge-bronze',
      progressRingColor: '#FF7043',
    },
    barcode: { format: 'QR_CODE', message: '', messageEncoding: 'iso-8859-1' },
    backContent: defaultBackContentDefaults.cashback,
    apple: {
      passStyle: 'storeCard',
      description: 'Cashback en café',
      organizationName: 'Café Cashback',
    },
    google: {
      passType: 'LoyaltyClass',
      programName: 'Café Cashback',
      hexBackgroundColor: '#3E2723',
    },
    tags: ['café', 'food', 'cashback'],
    createdAt: now,
    updatedAt: now,
  },

  /* ── 3. Retail Moderno ───────────────────────────────────────────── */
  {
    id: 'retail-moderno',
    name: 'Retail Moderno',
    description: 'Descuentos por niveles de compra',
    type: 'system',
    cardType: 'discount',
    industry: 'retail',
    colors: {
      background: '#FFFFFF',
      foreground: '#1A1A1A',
      label: '#666666',
      accent: '#E53935',
    },
    cardTypeConfig: {
      cardType: 'discount',
      tiers: [
        { tierName: 'Bronce', threshold: 0, discountPercentage: 5 },
        { tierName: 'Plata', threshold: 500, discountPercentage: 10 },
        { tierName: 'Oro', threshold: 1500, discountPercentage: 15 },
      ],
      tierBadgeIcons: ['badge-bronze', 'badge-silver', 'badge-gold'],
      progressBarColor: '#E53935',
      percentageDisplayStyle: 'badge',
      discountBannerText: 'Más compras, más ahorro',
    },
    barcode: { format: 'QR_CODE', message: '', messageEncoding: 'iso-8859-1' },
    backContent: defaultBackContentDefaults.discount,
    apple: {
      passStyle: 'storeCard',
      description: 'Descuentos por niveles',
      organizationName: 'Retail Moderno',
    },
    google: {
      passType: 'LoyaltyClass',
      programName: 'Retail Moderno VIP',
      hexBackgroundColor: '#FFFFFF',
    },
    tags: ['retail', 'discount'],
    createdAt: now,
    updatedAt: now,
  },

  /* ── 4. Gym Pro ──────────────────────────────────────────────────── */
  {
    id: 'gym-pro',
    name: 'Gym Pro',
    description: 'Membresía VIP Oro',
    type: 'system',
    cardType: 'vip_membership',
    industry: 'health',
    colors: {
      background: '#1A1A2E',
      foreground: '#FFFFFF',
      label: '#E94560',
      accent: '#E94560',
    },
    cardTypeConfig: {
      cardType: 'vip_membership',
      membershipName: 'Gym Pro VIP',
      monthlyFee: 49.99,
      annualFee: 499.99,
      validityPeriod: 'monthly',
      perks: ['Acceso ilimitado', 'Clases grupales', 'Sauna', 'Nutricionista'],
      crownIcon: 'crown-gold',
      memberBadgeStyle: 'gold',
      benefitsListIcons: ['dumbbell', 'users', 'flame', 'apple'],
    },
    barcode: { format: 'QR_CODE', message: '', messageEncoding: 'iso-8859-1' },
    backContent: defaultBackContentDefaults.vip_membership,
    apple: {
      passStyle: 'generic',
      description: 'Membresía Gym Pro',
      organizationName: 'Gym Pro',
    },
    google: {
      passType: 'LoyaltyClass',
      programName: 'Gym Pro Membership',
      hexBackgroundColor: '#1A1A2E',
    },
    tags: ['gym', 'health', 'vip'],
    createdAt: now,
    updatedAt: now,
  },

  /* ── 5. Salón de Belleza ─────────────────────────────────────────── */
  {
    id: 'salon-belleza',
    name: 'Salón de Belleza',
    description: 'Sellos: ✂️×8',
    type: 'system',
    cardType: 'stamp',
    industry: 'services',
    colors: {
      background: '#880E4F',
      foreground: '#FFFFFF',
      label: '#F8BBD0',
      accent: '#FF4081',
    },
    cardTypeConfig: {
      cardType: 'stamp',
      stampsRequired: 8,
      rewardDescription: 'Corte gratis',
      stampType: 'visit',
      consumptionPerStamp: 1,
      stampExpiry: 'unlimited',
      stampsAtIssue: 0,
      dailyStampLimit: 1,
      birthdayStamps: 1,
      stampShape: 'heart',
      stampIcon: 'scissors',
      stampFilledIcon: 'scissors-filled',
      stampColor: '#FF4081',
      stampGridLayout: '4x4',
    },
    barcode: { format: 'QR_CODE', message: '', messageEncoding: 'iso-8859-1' },
    backContent: defaultBackContentDefaults.stamp,
    apple: {
      passStyle: 'storeCard',
      description: 'Tarjeta de sellos salón',
      organizationName: 'Salón de Belleza',
    },
    google: {
      passType: 'LoyaltyClass',
      programName: 'Salón Belleza Rewards',
      hexBackgroundColor: '#880E4F',
    },
    tags: ['salón', 'services', 'stamp'],
    createdAt: now,
    updatedAt: now,
  },

  /* ── 6. Hotel Lujo ───────────────────────────────────────────────── */
  {
    id: 'hotel-lujo',
    name: 'Hotel Lujo',
    description: 'Membresía Club Ejecutivo',
    type: 'system',
    cardType: 'vip_membership',
    industry: 'services',
    colors: {
      background: '#1A1A1A',
      foreground: '#FFFFFF',
      label: '#B0B0B0',
      accent: '#C0A062',
    },
    cardTypeConfig: {
      cardType: 'vip_membership',
      membershipName: 'Club Ejecutivo',
      monthlyFee: 99,
      annualFee: 999,
      validityPeriod: 'annual',
      perks: ['Upgrade habitación', 'Desayuno incluido', 'Late checkout', 'Spa gratuito'],
      crownIcon: 'crown-platinum',
      memberBadgeStyle: 'platinum',
      benefitsListIcons: ['bed', 'coffee', 'clock', 'spa'],
    },
    barcode: { format: 'QR_CODE', message: '', messageEncoding: 'iso-8859-1' },
    backContent: defaultBackContentDefaults.vip_membership,
    apple: {
      passStyle: 'generic',
      description: 'Membresía Hotel Lujo',
      organizationName: 'Hotel Lujo',
    },
    google: {
      passType: 'LoyaltyClass',
      programName: 'Hotel Lujo Club',
      hexBackgroundColor: '#1A1A1A',
    },
    tags: ['hotel', 'services', 'vip'],
    createdAt: now,
    updatedAt: now,
  },

  /* ── 7. Food Truck Rápido ────────────────────────────────────────── */
  {
    id: 'foodtruck-rapido',
    name: 'Food Truck Rápido',
    description: 'Cupón: 2×1 en tacos',
    type: 'system',
    cardType: 'coupon',
    industry: 'food',
    colors: {
      background: '#FFF3E0',
      foreground: '#E65100',
      label: '#F57C00',
      accent: '#FF9800',
    },
    cardTypeConfig: {
      cardType: 'coupon',
      discountType: 'percentage',
      discountValue: 50,
      usageLimitPerCustomer: 2,
      couponDescription: '2×1 en todos los tacos',
      specialPromotionText: 'Válido de lunes a jueves',
      couponExpiry: 30,
      couponStartDate: undefined,
      couponEndDate: undefined,
      pushMessage: '¡Nuevos tacos esta semana!',
      cutLineStyle: 'dashed',
      discountBadgeStyle: 'banner',
      offerTag: '2×1',
    },
    barcode: { format: 'QR_CODE', message: '', messageEncoding: 'iso-8859-1' },
    backContent: defaultBackContentDefaults.coupon,
    apple: {
      passStyle: 'coupon',
      description: 'Cupón Food Truck',
      organizationName: 'Food Truck Rápido',
    },
    google: {
      passType: 'OfferClass',
      programName: 'Food Truck Ofertas',
      hexBackgroundColor: '#FFF3E0',
    },
    tags: ['food truck', 'food', 'coupon'],
    createdAt: now,
    updatedAt: now,
  },

  /* ── 8. Librería Sabiduría ───────────────────────────────────────── */
  {
    id: 'libreria-sabiduria',
    name: 'Librería Sabiduría',
    description: 'Sellos: 📚×12',
    type: 'system',
    cardType: 'stamp',
    industry: 'retail',
    colors: {
      background: '#1B5E20',
      foreground: '#FFFFFF',
      label: '#C8E6C9',
      accent: '#69F0AE',
    },
    cardTypeConfig: {
      cardType: 'stamp',
      stampsRequired: 12,
      rewardDescription: 'Libro gratuito',
      stampType: 'consumption',
      consumptionPerStamp: 200,
      stampExpiry: 'unlimited',
      stampsAtIssue: 0,
      dailyStampLimit: 5,
      birthdayStamps: 2,
      stampShape: 'diamond',
      stampIcon: 'book',
      stampFilledIcon: 'book-filled',
      stampColor: '#69F0AE',
      stampGridLayout: '6x2',
    },
    barcode: { format: 'QR_CODE', message: '', messageEncoding: 'iso-8859-1' },
    backContent: defaultBackContentDefaults.stamp,
    apple: {
      passStyle: 'storeCard',
      description: 'Tarjeta de sellos librería',
      organizationName: 'Librería Sabiduría',
    },
    google: {
      passType: 'LoyaltyClass',
      programName: 'Librería Sabiduría Rewards',
      hexBackgroundColor: '#1B5E20',
    },
    tags: ['bookstore', 'retail', 'stamp'],
    createdAt: now,
    updatedAt: now,
  },

  /* ── 9. Farmacia Salud ───────────────────────────────────────────── */
  {
    id: 'farmacia-salud',
    name: 'Farmacia Salud',
    description: 'Descuentos progresivos',
    type: 'system',
    cardType: 'discount',
    industry: 'health',
    colors: {
      background: '#E8F5E9',
      foreground: '#1B5E20',
      label: '#388E3C',
      accent: '#4CAF50',
    },
    cardTypeConfig: {
      cardType: 'discount',
      tiers: [
        { tierName: 'Cliente', threshold: 0, discountPercentage: 3 },
        { tierName: 'Frecuente', threshold: 300, discountPercentage: 7 },
        { tierName: 'VIP', threshold: 800, discountPercentage: 12 },
      ],
      tierBadgeIcons: ['badge-green', 'badge-teal', 'badge-emerald'],
      progressBarColor: '#4CAF50',
      percentageDisplayStyle: 'expanded',
      discountBannerText: 'Tu salud, tu ahorro',
    },
    barcode: { format: 'QR_CODE', message: '', messageEncoding: 'iso-8859-1' },
    backContent: defaultBackContentDefaults.discount,
    apple: {
      passStyle: 'storeCard',
      description: 'Descuentos Farmacia Salud',
      organizationName: 'Farmacia Salud',
    },
    google: {
      passType: 'LoyaltyClass',
      programName: 'Farmacia Salud VIP',
      hexBackgroundColor: '#E8F5E9',
    },
    tags: ['pharmacy', 'health', 'discount'],
    createdAt: now,
    updatedAt: now,
  },

  /* ── 10. Pet Shop Mascotas ───────────────────────────────────────── */
  {
    id: 'petshop-mascotas',
    name: 'Pet Shop Mascotas',
    description: 'Sellos: 🐾×10',
    type: 'system',
    cardType: 'stamp',
    industry: 'retail',
    colors: {
      background: '#F3E5F5',
      foreground: '#4A148C',
      label: '#7B1FA2',
      accent: '#9C27B0',
    },
    cardTypeConfig: {
      cardType: 'stamp',
      stampsRequired: 10,
      rewardDescription: 'Baño gratis',
      stampType: 'visit',
      consumptionPerStamp: 1,
      stampExpiry: 'unlimited',
      stampsAtIssue: 0,
      dailyStampLimit: 2,
      birthdayStamps: 1,
      stampShape: 'hexagon',
      stampIcon: 'paw',
      stampFilledIcon: 'paw-filled',
      stampColor: '#9C27B0',
      stampGridLayout: '5x2',
    },
    barcode: { format: 'QR_CODE', message: '', messageEncoding: 'iso-8859-1' },
    backContent: defaultBackContentDefaults.stamp,
    apple: {
      passStyle: 'storeCard',
      description: 'Tarjeta de sellos mascotas',
      organizationName: 'Pet Shop Mascotas',
    },
    google: {
      passType: 'LoyaltyClass',
      programName: 'Pet Shop Rewards',
      hexBackgroundColor: '#F3E5F5',
    },
    tags: ['pet shop', 'retail', 'stamp'],
    createdAt: now,
    updatedAt: now,
  },
];
