/**
 * System template definitions — batch 2 (templates 11–20).
 *
 * Extracted from registry.ts to keep each file under the 650-line project limit.
 */

import type { WalletTemplate } from '@/components/wallet/types/templates';
import { defaultBackContentDefaults } from '@/components/wallet/types/back-content';

const now = new Date().toISOString();

export const SYSTEM_TEMPLATES_02: WalletTemplate[] = [
  /* ── 11. Panadería Dulce ─────────────────────────────────────────── */
  {
    id: 'panaderia-dulce',
    name: 'Panadería Dulce',
    description: 'Sellos: 🥐×8',
    type: 'system',
    cardType: 'stamp',
    industry: 'food',
    colors: {
      background: '#FFF8E1',
      foreground: '#3E2723',
      label: '#8D6E63',
      accent: '#FF6F00',
    },
    cardTypeConfig: {
      cardType: 'stamp',
      stampsRequired: 8,
      rewardDescription: 'Docena de medialunas',
      stampType: 'consumption',
      consumptionPerStamp: 100,
      stampExpiry: 'unlimited',
      stampsAtIssue: 1,
      dailyStampLimit: 3,
      birthdayStamps: 2,
      stampShape: 'star',
      stampIcon: 'croissant',
      stampFilledIcon: 'croissant-filled',
      stampColor: '#FF6F00',
      stampGridLayout: '4x4',
    },
    barcode: { format: 'QR_CODE', message: '', messageEncoding: 'iso-8859-1' },
    backContent: defaultBackContentDefaults.stamp,
    apple: {
      passStyle: 'storeCard',
      description: 'Tarjeta de sellos panadería',
      organizationName: 'Panadería Dulce',
    },
    google: {
      passType: 'LoyaltyClass',
      programName: 'Panadería Dulce Rewards',
      hexBackgroundColor: '#FFF8E1',
    },
    tags: ['bakery', 'food', 'stamp'],
    createdAt: now,
    updatedAt: now,
  },

  /* ── 12. Restaurante Gourmet ─────────────────────────────────────── */
  {
    id: 'restaurante-gourmet',
    name: 'Restaurante Gourmet',
    description: 'Cashback 8% en cenas',
    type: 'system',
    cardType: 'cashback',
    industry: 'food',
    colors: {
      background: '#37474F',
      foreground: '#FFFFFF',
      label: '#B0BEC5',
      accent: '#26A69A',
    },
    cardTypeConfig: {
      cardType: 'cashback',
      cashbackPercentage: 8,
      minimumPurchase: 100,
      creditExpiryDays: 180,
      creditExpiryType: 'defined_period' as const,
      tierName: 'Gourmet',
      coinIcon: 'coin-silver',
      tierBadge: 'badge-silver',
      progressRingColor: '#26A69A',
    },
    barcode: { format: 'QR_CODE', message: '', messageEncoding: 'iso-8859-1' },
    backContent: defaultBackContentDefaults.cashback,
    apple: {
      passStyle: 'storeCard',
      description: 'Cashback Restaurante Gourmet',
      organizationName: 'Restaurante Gourmet',
    },
    google: {
      passType: 'LoyaltyClass',
      programName: 'Gourmet Rewards',
      hexBackgroundColor: '#37474F',
    },
    tags: ['restaurant', 'food', 'cashback'],
    createdAt: now,
    updatedAt: now,
  },

  /* ── 13. Barbería Clásica ────────────────────────────────────────── */
  {
    id: 'barberia-clasica',
    name: 'Barbería Clásica',
    description: 'Multi-pase: 5 cortes',
    type: 'system',
    cardType: 'multipass',
    industry: 'services',
    colors: {
      background: '#0D1117',
      foreground: '#C9D1D9',
      label: '#8B949E',
      accent: '#58A6FF',
    },
    cardTypeConfig: {
      cardType: 'multipass',
      bundleSize: 5,
      bundlePrice: 200,
      passTypeLabel: 'Corte + Barba',
      ticketGraphic: 'ticket-barber',
      punchIcon: 'check',
      bundleBadgeStyle: 'visual',
      indicatorStyle: 'visual',
    },
    barcode: { format: 'QR_CODE', message: '', messageEncoding: 'iso-8859-1' },
    backContent: defaultBackContentDefaults.multipass,
    apple: {
      passStyle: 'eventTicket',
      description: 'Multi-pase Barbería',
      organizationName: 'Barbería Clásica',
    },
    google: {
      passType: 'GenericClass',
      programName: 'Barbería Clásica Pass',
      hexBackgroundColor: '#0D1117',
    },
    tags: ['barber', 'services', 'multipass'],
    createdAt: now,
    updatedAt: now,
  },

  /* ── 14. Spa Relax ───────────────────────────────────────────────── */
  {
    id: 'spa-relax',
    name: 'Spa Relax',
    description: 'Certificado de regalo',
    type: 'system',
    cardType: 'gift_certificate',
    industry: 'health',
    colors: {
      background: '#EDE7F6',
      foreground: '#311B92',
      label: '#5E35B1',
      accent: '#7C4DFF',
    },
    cardTypeConfig: {
      cardType: 'gift_certificate',
      denominations: [50, 100, 200, 500],
      expiryDays: 365,
      boxGraphic: 'gift-box-lavender',
      ribbonColor: '#7C4DFF',
      occasion: 'Cumpleaños',
      denominationBadge: 'gift-badge',
    },
    barcode: { format: 'QR_CODE', message: '', messageEncoding: 'iso-8859-1' },
    backContent: defaultBackContentDefaults.gift_certificate,
    apple: {
      passStyle: 'storeCard',
      description: 'Certificado Spa Relax',
      organizationName: 'Spa Relax',
    },
    google: {
      passType: 'GiftCardClass',
      programName: 'Spa Relax Gift',
      hexBackgroundColor: '#EDE7F6',
    },
    tags: ['spa', 'health', 'gift'],
    createdAt: now,
    updatedAt: now,
  },

  /* ── 15. Cine Estrella ───────────────────────────────────────────── */
  {
    id: 'cine-estrella',
    name: 'Cine Estrella',
    description: 'Multi-pase: 10 entradas',
    type: 'system',
    cardType: 'multipass',
    industry: 'entertainment',
    colors: {
      background: '#311B92',
      foreground: '#FFFFFF',
      label: '#D1C4E9',
      accent: '#E040FB',
    },
    cardTypeConfig: {
      cardType: 'multipass',
      bundleSize: 10,
      bundlePrice: 350,
      passTypeLabel: 'Entrada General',
      ticketGraphic: 'ticket-cinema',
      punchIcon: 'popcorn',
      bundleBadgeStyle: 'numeric',
      indicatorStyle: 'numeric',
    },
    barcode: { format: 'QR_CODE', message: '', messageEncoding: 'iso-8859-1' },
    backContent: defaultBackContentDefaults.multipass,
    apple: {
      passStyle: 'eventTicket',
      description: 'Multi-pase Cine Estrella',
      organizationName: 'Cine Estrella',
    },
    google: {
      passType: 'GenericClass',
      programName: 'Cine Estrella Pass',
      hexBackgroundColor: '#311B92',
    },
    tags: ['cinema', 'entertainment', 'multipass'],
    createdAt: now,
    updatedAt: now,
  },

  /* ── 16. Parking Ciudad ──────────────────────────────────────────── */
  {
    id: 'parking-ciudad',
    name: 'Parking Ciudad',
    description: 'Multi-pase: 20 usos',
    type: 'system',
    cardType: 'multipass',
    industry: 'transport',
    colors: {
      background: '#01579B',
      foreground: '#FFFFFF',
      label: '#B3E5FC',
      accent: '#03A9F4',
    },
    cardTypeConfig: {
      cardType: 'multipass',
      bundleSize: 20,
      bundlePrice: 400,
      passTypeLabel: 'Estacionamiento',
      ticketGraphic: 'ticket-parking',
      punchIcon: 'car',
      bundleBadgeStyle: 'minimal',
      indicatorStyle: 'minimal',
    },
    barcode: { format: 'QR_CODE', message: '', messageEncoding: 'iso-8859-1' },
    backContent: defaultBackContentDefaults.multipass,
    apple: {
      passStyle: 'eventTicket',
      description: 'Multi-pase Parking',
      organizationName: 'Parking Ciudad',
    },
    google: {
      passType: 'GenericClass',
      programName: 'Parking Ciudad Pass',
      hexBackgroundColor: '#01579B',
    },
    tags: ['parking', 'transport', 'multipass'],
    createdAt: now,
    updatedAt: now,
  },

  /* ── 17. Lavandería Fresh ────────────────────────────────────────── */
  {
    id: 'lavanderia-fresh',
    name: 'Lavandería Fresh',
    description: 'Sellos: 👕×10',
    type: 'system',
    cardType: 'stamp',
    industry: 'services',
    colors: {
      background: '#E0F7FA',
      foreground: '#006064',
      label: '#00838F',
      accent: '#00BCD4',
    },
    cardTypeConfig: {
      cardType: 'stamp',
      stampsRequired: 10,
      rewardDescription: 'Lavado gratis',
      stampType: 'consumption',
      consumptionPerStamp: 50,
      stampExpiry: 'unlimited',
      stampsAtIssue: 0,
      dailyStampLimit: 5,
      birthdayStamps: 1,
      stampShape: 'square',
      stampIcon: 'shirt',
      stampFilledIcon: 'shirt-filled',
      stampColor: '#00BCD4',
      stampGridLayout: '5x2',
    },
    barcode: { format: 'QR_CODE', message: '', messageEncoding: 'iso-8859-1' },
    backContent: defaultBackContentDefaults.stamp,
    apple: {
      passStyle: 'storeCard',
      description: 'Tarjeta de sellos lavandería',
      organizationName: 'Lavandería Fresh',
    },
    google: {
      passType: 'LoyaltyClass',
      programName: 'Lavandería Fresh Rewards',
      hexBackgroundColor: '#E0F7FA',
    },
    tags: ['laundry', 'services', 'stamp'],
    createdAt: now,
    updatedAt: now,
  },

  /* ── 18. Floristería Ramo ────────────────────────────────────────── */
  {
    id: 'floristeria-ramo',
    name: 'Floristería Ramo',
    description: 'Certificado de regalo floral',
    type: 'system',
    cardType: 'gift_certificate',
    industry: 'retail',
    colors: {
      background: '#FFF0F5',
      foreground: '#880E4F',
      label: '#C2185B',
      accent: '#F48FB1',
    },
    cardTypeConfig: {
      cardType: 'gift_certificate',
      denominations: [25, 50, 100],
      expiryDays: 180,
      boxGraphic: 'gift-box-rose',
      ribbonColor: '#F48FB1',
      occasion: 'Aniversario',
      denominationBadge: 'rose-badge',
    },
    barcode: { format: 'QR_CODE', message: '', messageEncoding: 'iso-8859-1' },
    backContent: defaultBackContentDefaults.gift_certificate,
    apple: {
      passStyle: 'storeCard',
      description: 'Certificado Floristería Ramo',
      organizationName: 'Floristería Ramo',
    },
    google: {
      passType: 'GiftCardClass',
      programName: 'Floristería Ramo Gift',
      hexBackgroundColor: '#FFF0F5',
    },
    tags: ['florist', 'retail', 'gift'],
    createdAt: now,
    updatedAt: now,
  },

  /* ── 19. Tech Store Digital ──────────────────────────────────────── */
  {
    id: 'techstore-digital',
    name: 'Tech Store Digital',
    description: 'Descuentos por niveles tech',
    type: 'system',
    cardType: 'discount',
    industry: 'technology',
    colors: {
      background: '#0D1117',
      foreground: '#C9D1D9',
      label: '#8B949E',
      accent: '#58A6FF',
    },
    cardTypeConfig: {
      cardType: 'discount',
      tiers: [
        { tierName: 'Explorer', threshold: 0, discountPercentage: 3 },
        { tierName: 'Pro', threshold: 1000, discountPercentage: 8 },
        { tierName: 'Elite', threshold: 3000, discountPercentage: 15 },
      ],
      tierBadgeIcons: ['badge-copper', 'badge-silver', 'badge-gold'],
      progressBarColor: '#58A6FF',
      percentageDisplayStyle: 'compact',
      discountBannerText: 'Tecnología al mejor precio',
    },
    barcode: { format: 'QR_CODE', message: '', messageEncoding: 'iso-8859-1' },
    backContent: defaultBackContentDefaults.discount,
    apple: {
      passStyle: 'storeCard',
      description: 'Descuentos Tech Store',
      organizationName: 'Tech Store Digital',
    },
    google: {
      passType: 'LoyaltyClass',
      programName: 'Tech Store VIP',
      hexBackgroundColor: '#0D1117',
    },
    tags: ['tech store', 'technology', 'discount'],
    createdAt: now,
    updatedAt: now,
  },

  /* ── 20. Supermercado Ahorro ─────────────────────────────────────── */
  {
    id: 'supermercado-ahorro',
    name: 'Supermercado Ahorro',
    description: 'Cashback 3% en todas las compras',
    type: 'system',
    cardType: 'cashback',
    industry: 'retail',
    colors: {
      background: '#2E8B57',
      foreground: '#FFFFFF',
      label: '#90EE90',
      accent: '#3CB371',
    },
    cardTypeConfig: {
      cardType: 'cashback',
      cashbackPercentage: 3,
      minimumPurchase: 0,
      creditExpiryDays: 90,
      creditExpiryType: 'defined_period' as const,
      tierName: 'Ahorrador',
      coinIcon: 'coin-gold',
      tierBadge: 'badge-green',
      progressRingColor: '#3CB371',
    },
    barcode: { format: 'QR_CODE', message: '', messageEncoding: 'iso-8859-1' },
    backContent: defaultBackContentDefaults.cashback,
    apple: {
      passStyle: 'storeCard',
      description: 'Cashback Supermercado Ahorro',
      organizationName: 'Supermercado Ahorro',
    },
    google: {
      passType: 'LoyaltyClass',
      programName: 'Supermercado Ahorro Rewards',
      hexBackgroundColor: '#2E8B57',
    },
    tags: ['supermarket', 'retail', 'cashback'],
    createdAt: now,
    updatedAt: now,
  },
];
