# Generated by Django 5.0.6 on 2026-04-22 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_subscriptionplan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='claro_pay_charge_id',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='claro_pay_token',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='claro_pay_customer_id',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='claro_pay_subscription_id',
        ),
        migrations.AddField(
            model_name='invoice',
            name='gateway_charge_id',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='ID de cargo (gateway)'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='gateway_token',
            field=models.CharField(default='', max_length=200, verbose_name='Token de pago (gateway)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='gateway_customer_id',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='ID de cliente (gateway)'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='gateway_subscription_id',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='ID de suscripción (gateway)'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='subscription_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='billing.subscriptionplan', verbose_name='Plan de suscripción'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_notifications_month',
            field=models.PositiveIntegerField(default=1000, verbose_name='Máx. notificaciones/mes'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_transactions_month',
            field=models.PositiveIntegerField(default=5000, verbose_name='Máx. transacciones/mes'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(default='trial', max_length=20, verbose_name='Plan (legacy)'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='features',
            field=models.JSONField(default=list, help_text='List of PlanFeature flags: geo_fencing, automation, ai_assistant, etc.', verbose_name='Características incluidas'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='trial_days',
            field=models.PositiveIntegerField(default=5, verbose_name='Días de prueba'),
        ),
    ]
