# Generated by Django 5.0.6 on 2026-05-01 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_webhookevent"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscription",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Suscripción",
                "verbose_name_plural": "Suscripciones",
            },
        ),
        migrations.RenameIndex(
            model_name="webhookevent",
            new_name="lyl_webhook_event_i_7fa6ab_idx",
            old_name="lyl_webhook_event_id_idx",
        ),
        migrations.RenameIndex(
            model_name="webhookevent",
            new_name="lyl_webhook_process_88196f_idx",
            old_name="lyl_webhook_processed_idx",
        ),
    ]
