# Generated by Django 5.0.6 on 2026-05-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0003_alter_subscription_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="trial_extended_count",
            field=models.SmallIntegerField(
                default=0, verbose_name="Extensiones de trial"
            ),
        ),
    ]
