# Generated by Django 5.0.6 on 2026-05-05 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0004_subscription_trial_extended_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionplan",
            name="max_emails_month",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Monthly email campaign quota via Listmonk. 0=disabled.",
                verbose_name="Máx. emails/mes",
            ),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="max_whatsapp_day",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Daily WhatsApp message limit. 0=disabled. Safe ceiling: 200 (Baileys anti-ban).",
                verbose_name="Máx. WhatsApp/día",
            ),
        ),
    ]
