# Generated by Django 5.0.6 on 2026-05-05 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_plan_messaging_gating'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_sms_day',
            field=models.PositiveIntegerField(default=0, help_text='Daily SMS quota via Twilio. 0=disabled.', verbose_name='Máx. SMS/día'),
        ),
    ]
