# Generated by Django 5.0.6 on 2026-05-18 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0009_subscriptionplan_status"),
        ("tenants", "0009_alter_tenant_scheduled_deletion_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="subscription",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoices",
                to="billing.subscription",
                verbose_name="Suscripción",
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["tenant", "status"], name="loyallia_in_tenant__316a5a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(fields=["status"], name="loyallia_su_status_3663ba_idx"),
        ),
    ]
