# Generated by Django 5.2.14 on 2026-06-03 20:35

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_alter_invoice_subscription_and_more'),
        ('tenants', '0011_alter_location_address_alter_location_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='billing_cycle',
            field=models.CharField(choices=[('monthly', 'Mensual'), ('annual', 'Anual')], default='monthly', help_text='Billing frequency (monthly or annual).', max_length=10, verbose_name='Ciclo de facturación'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='cancel_at_period_end',
            field=models.BooleanField(default=False, help_text='Whether to cancel at the end of the period.', verbose_name='Cancelar al final del período'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='canceled_at',
            field=models.DateTimeField(blank=True, help_text='When the subscription was canceled.', null=True, verbose_name='Cancelado en'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='current_period_end',
            field=models.DateTimeField(blank=True, help_text='End of the current billing period.', null=True, verbose_name='Fin del período actual'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='current_period_start',
            field=models.DateTimeField(blank=True, help_text='Start of the current billing period.', null=True, verbose_name='Inicio del período actual'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='failed_payment_count',
            field=models.SmallIntegerField(default=0, help_text='Number of failed payment attempts.', verbose_name='Intentos de pago fallidos'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='gateway_customer_id',
            field=models.CharField(blank=True, default='', help_text='Customer ID from the payment gateway.', max_length=100, verbose_name='ID de cliente (gateway)'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='gateway_subscription_id',
            field=models.CharField(blank=True, default='', help_text='Subscription ID from the payment gateway.', max_length=100, verbose_name='ID de suscripción (gateway)'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='last_payment_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the last successful payment.', null=True, verbose_name='Último pago exitoso'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='last_payment_error',
            field=models.TextField(blank=True, default='', help_text='Details of the last payment failure.', verbose_name='Último error de pago'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(default='trial', help_text='Subscription or pricing plan.', max_length=20, verbose_name='Plan (legacy)'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('trialing', 'Período de prueba'), ('active', 'Activo'), ('past_due', 'Pago pendiente'), ('suspended', 'Suspendido'), ('canceled', 'Cancelado')], default='trialing', help_text='Current status of this record.', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscription_plan',
            field=models.ForeignKey(blank=True, help_text='The subscription plan defining limits and pricing.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='billing.subscriptionplan', verbose_name='Plan de suscripción'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='tenant',
            field=models.OneToOneField(help_text='The business this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='tenants.tenant', verbose_name='Negocio'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='trial_end',
            field=models.DateTimeField(blank=True, help_text='End date of the trial period.', null=True, verbose_name='Fin del trial'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='trial_extended_count',
            field=models.SmallIntegerField(default=0, help_text='Count or tally.', verbose_name='Extensiones de trial'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='trial_start',
            field=models.DateTimeField(blank=True, help_text='Trial start.', null=True, verbose_name='Inicio del trial'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Description of this record.', verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this record is currently active.', verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Whether this plan is highlighted as recommended.', verbose_name='Plan recomendado'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='max_customers',
            field=models.PositiveIntegerField(default=500, help_text='Maximum allowed customers.', verbose_name='Máx. clientes'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='max_locations',
            field=models.PositiveIntegerField(default=1, help_text='Maximum allowed locations.', verbose_name='Máx. sucursales'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='max_notifications_month',
            field=models.PositiveIntegerField(default=1000, help_text='Maximum notifications per month.', verbose_name='Máx. notificaciones/mes'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='max_programs',
            field=models.PositiveIntegerField(default=1, help_text='Maximum allowed programs.', verbose_name='Máx. programas'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='max_transactions_month',
            field=models.PositiveIntegerField(default=5000, help_text='Maximum transactions per month.', verbose_name='Máx. transacciones/mes'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='max_users',
            field=models.PositiveIntegerField(default=3, help_text='Maximum allowed users.', verbose_name='Máx. usuarios'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='name',
            field=models.CharField(help_text='Name of this record.', max_length=100, verbose_name='Nombre del plan'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='price_annual',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Annual price in USD.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio anual (USD)'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='price_monthly',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monthly price in USD.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio mensual (USD)'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='slug',
            field=models.SlugField(help_text='URL-friendly unique identifier.', unique=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0, help_text='Display order.', verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='trial_days',
            field=models.PositiveIntegerField(default=5, help_text='Number of days in the trial period.', verbose_name='Días de prueba'),
        ),
    ]
