# Generated by Django 5.2.14 on 2026-06-03 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0011_alter_subscription_billing_cycle_and_more"),
        ("tenants", "0011_alter_location_address_alter_location_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="invoice_number",
            field=models.CharField(max_length=50, verbose_name="Número de factura"),
        ),
        migrations.AlterUniqueTogether(
            name="invoice",
            unique_together={("tenant", "invoice_number")},
        ),
        migrations.CreateModel(
            name="InvoiceCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_number",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Último número"
                    ),
                ),
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice_counter",
                        to="tenants.tenant",
                        verbose_name="Negocio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contador de facturas",
                "verbose_name_plural": "Contadores de facturas",
                "db_table": "loyallia_invoice_counters",
            },
        ),
    ]
