# Generated by Django 5.2.14 on 2026-06-03 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0013_invoice_check_invoice_subtotal_non_negative_and_more"),
        ("tenants", "0011_alter_location_address_alter_location_city_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="paymentmethod",
            index=models.Index(
                fields=["tenant", "is_default"], name="loyallia_pa_tenant__e20efb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["tenant"], name="loyallia_su_tenant__7ed091_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscriptionplan",
            index=models.Index(
                fields=["is_active", "status"], name="loyallia_su_is_acti_2405d1_idx"
            ),
        ),
    ]
