# Generated by Django 5.2.15 on 2026-06-04 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0014_paymentmethod_loyallia_pa_tenant__e20efb_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_wallet_pass_updates_month',
            field=models.PositiveIntegerField(default=0, help_text='Monthly wallet pass update quota. 0=disabled.', verbose_name='Máx. actualizaciones wallet/mes'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_wallet_templates',
            field=models.PositiveIntegerField(default=0, help_text='Maximum wallet pass templates a tenant can create. 0=disabled.', verbose_name='Máx. plantillas wallet'),
        ),
    ]
