# Generated by Django 5.2.15 on 2026-10-07 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0015_subscriptionplan_max_wallet_pass_updates_month_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionplan",
            name="max_whatsapp_accounts",
            field=models.PositiveIntegerField(
                default=1,
                help_text="How many WhatsApp numbers can be linked to this business. Each number is paired via QR by a user. Anti-ban ceiling 200/day per number.",
                verbose_name="Máx. cuentas WhatsApp",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="max_whatsapp_day",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Daily WhatsApp message POOL for the whole business (all linked accounts). 0=disabled. Safe ceiling: 200 per number × accounts.",
                verbose_name="Máx. WhatsApp/día",
            ),
        ),
    ]
