# Generated by Django 5.2.14 on 2026-06-03 20:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0007_alter_user_role_and_more"),
        ("tenants", "0011_alter_location_address_alter_location_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="refreshtoken",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Timestamp for created."
            ),
        ),
        migrations.AlterField(
            model_name="refreshtoken",
            name="device_name",
            field=models.CharField(
                blank=True, default="", help_text="Name of the device.", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="refreshtoken",
            name="expires_at",
            field=models.DateTimeField(help_text="Timestamp for expires."),
        ),
        migrations.AlterField(
            model_name="refreshtoken",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Unique identifier for this record.",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="refreshtoken",
            name="revoked_at",
            field=models.DateTimeField(
                blank=True, help_text="Timestamp for revoked.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="refreshtoken",
            name="token_hash",
            field=models.CharField(
                help_text="Token for authentication or verification.",
                max_length=64,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="refreshtoken",
            name="user",
            field=models.ForeignKey(
                help_text="The user associated with this record.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="refresh_tokens",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="date_joined",
            field=models.DateTimeField(auto_now_add=True, help_text="Date joined."),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                help_text="Email address.", max_length=254, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="failed_login_count",
            field=models.SmallIntegerField(
                default=0, help_text="Number of consecutive failed login attempts."
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True, default="", help_text="First name.", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Unique identifier for this record.",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="invitation_accepted_at",
            field=models.DateTimeField(
                blank=True, help_text="When the invitation was accepted.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="invitation_token",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Token for tracking invitations.",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="invited_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who invited this person.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invited_users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Whether this record is currently active."
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_email_verified",
            field=models.BooleanField(
                default=False, help_text="Whether the email address has been verified."
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_phone_verified",
            field=models.BooleanField(
                default=False, help_text="Whether the phone number has been verified."
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(
                default=False, help_text="Whether the user can access the Django admin."
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp of the last successful login.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                blank=True, default="", help_text="Last name.", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="locked_until",
            field=models.DateTimeField(
                blank=True, help_text="Account lockout expiration time.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("SUPER_ADMIN", "Super Administrador"),
                    ("OWNER", "Propietario"),
                    ("MANAGER", "Gerente"),
                    ("STAFF", "Personal"),
                ],
                db_index=True,
                default="STAFF",
                help_text="Role or permission level.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="The business this record belongs to.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="tenants.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Timestamp for updated."
            ),
        ),
    ]
