upstream django_api {
    server 127.0.0.1:33905;
    keepalive 32;
}

upstream nextjs_web {
    server 127.0.0.1:33906;
    keepalive 16;
}

server {
    listen 80;
    server_name rewards.loyallia.com;

    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_buffering off;

    location /api/ {
        proxy_pass http://django_api;
    }

    location / {
        proxy_pass http://nextjs_web;
    }
}
