# Generated by Django 5.2.15 on 2026-06-08 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0002_add_wallet_pass_operation_log"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="walletpassoperationlog",
            new_name="wallet_pass_tenant__5de2d6_idx",
            old_name="wallet_oplog_tenant_type_created_idx",
        ),
        migrations.RenameIndex(
            model_name="walletpassoperationlog",
            new_name="wallet_pass_tenant__36b485_idx",
            old_name="wallet_oplog_tenant_created_idx",
        ),
        migrations.RenameIndex(
            model_name="wallettemplate",
            new_name="wallet_temp_tenant__52e34d_idx",
            old_name="wallet_temp_tenant_own_fav_idx",
        ),
        migrations.RenameIndex(
            model_name="wallettemplate",
            new_name="wallet_temp_tenant__deb865_idx",
            old_name="wallet_temp_tenant_card_idx",
        ),
        migrations.RenameIndex(
            model_name="wallettemplate",
            new_name="wallet_temp_is_syst_59eb49_idx",
            old_name="wallet_temp_system_ind_idx",
        ),
    ]
