# Generated by Django 5.0.6 on 2026-05-05 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="automation",
            name="action",
            field=models.CharField(
                choices=[
                    ("send_notification", "Send Push Notification"),
                    ("send_email", "Send Email"),
                    ("send_sms", "Send SMS (Twilio)"),
                    ("send_whatsapp", "Send WhatsApp"),
                    ("issue_reward", "Issue Reward"),
                    ("update_segment", "Update Segment"),
                    ("send_wallet", "Send Wallet Push"),
                ],
                max_length=30,
                verbose_name="Acción",
            ),
        ),
    ]
