# Generated by Django 5.0.6 on 2026-05-18 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0002_alter_automation_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automation',
            name='action',
            field=models.CharField(choices=[('send_notification', 'Send Push Notification'), ('send_email', 'Send Email'), ('send_sms', 'Send SMS (Twilio)'), ('send_whatsapp', 'Send WhatsApp'), ('issue_reward', 'Issue Reward'), ('update_segment', 'Update Segment'), ('send_wallet', 'Send Wallet Push'), ('trigger_webhook', 'Trigger Webhook')], max_length=30, verbose_name='Acción'),
        ),
        migrations.AlterField(
            model_name='automation',
            name='trigger',
            field=models.CharField(choices=[('customer_enrolled', 'Customer Enrolled'), ('transaction_completed', 'Transaction Completed'), ('reward_earned', 'Reward Earned'), ('reward_ready', 'Reward Ready'), ('birthday_coming', 'Birthday Coming'), ('inactive_reminder', 'Inactive Reminder'), ('milestone_reached', 'Milestone Reached'), ('points_threshold', 'Points Threshold'), ('scheduled_time', 'Scheduled Time')], max_length=30, verbose_name='Disparador'),
        ),
    ]
