# Generated by Django 5.2.14 on 2026-06-03 20:35

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0003_alter_automation_action_alter_automation_trigger"),
        ("cards", "0010_alter_card_background_color_alter_card_barcode_type_and_more"),
        ("customers", "0010_alter_applepassregistration_customer_pass_and_more"),
        ("tenants", "0011_alter_location_address_alter_location_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="automation",
            name="action",
            field=models.CharField(
                choices=[
                    ("send_notification", "Send Push Notification"),
                    ("send_email", "Send Email"),
                    ("send_sms", "Send SMS (Twilio)"),
                    ("send_whatsapp", "Send WhatsApp"),
                    ("issue_reward", "Issue Reward"),
                    ("update_segment", "Update Segment"),
                    ("send_wallet", "Send Wallet Push"),
                    ("trigger_webhook", "Trigger Webhook"),
                ],
                help_text="Action performed.",
                max_length=30,
                verbose_name="Acción",
            ),
        ),
        migrations.AlterField(
            model_name="automation",
            name="action_config",
            field=models.JSONField(
                default=dict,
                help_text="Action configuration stored as JSON.",
                verbose_name="Configuración de la acción",
            ),
        ),
        migrations.AlterField(
            model_name="automation",
            name="cooldown_hours",
            field=models.PositiveIntegerField(
                default=24,
                help_text="Minimum hours between executions for the same customer.",
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Horas de enfriamiento",
            ),
        ),
        migrations.AlterField(
            model_name="automation",
            name="description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Description of this record.",
                verbose_name="Descripción",
            ),
        ),
        migrations.AlterField(
            model_name="automation",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Whether this record is currently active.",
                verbose_name="Activo",
            ),
        ),
        migrations.AlterField(
            model_name="automation",
            name="last_executed",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp of the most recent execution.",
                null=True,
                verbose_name="Última ejecución",
            ),
        ),
        migrations.AlterField(
            model_name="automation",
            name="max_executions_per_day",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Maximum executions allowed per day.",
                null=True,
                verbose_name="Ejecuciones máximas por día",
            ),
        ),
        migrations.AlterField(
            model_name="automation",
            name="name",
            field=models.CharField(
                help_text="Name of this record.", max_length=200, verbose_name="Nombre"
            ),
        ),
        migrations.AlterField(
            model_name="automation",
            name="schedule_config",
            field=models.JSONField(
                default=dict,
                help_text="Schedule configuration stored as JSON.",
                verbose_name="Configuración de horario",
            ),
        ),
        migrations.AlterField(
            model_name="automation",
            name="target_programs",
            field=models.ManyToManyField(
                blank=True,
                help_text="Target programs.",
                related_name="automations",
                to="cards.card",
                verbose_name="Programas objetivo",
            ),
        ),
        migrations.AlterField(
            model_name="automation",
            name="target_segments",
            field=models.JSONField(
                default=list,
                help_text="Target customer segments.",
                verbose_name="Segmentos objetivo",
            ),
        ),
        migrations.AlterField(
            model_name="automation",
            name="tenant",
            field=models.ForeignKey(
                help_text="The business this record belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="automations",
                to="tenants.tenant",
                verbose_name="Negocio",
            ),
        ),
        migrations.AlterField(
            model_name="automation",
            name="total_executions",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Total number of executions.",
                verbose_name="Ejecuciones totales",
            ),
        ),
        migrations.AlterField(
            model_name="automation",
            name="trigger",
            field=models.CharField(
                choices=[
                    ("customer_enrolled", "Customer Enrolled"),
                    ("transaction_completed", "Transaction Completed"),
                    ("reward_earned", "Reward Earned"),
                    ("reward_ready", "Reward Ready"),
                    ("birthday_coming", "Birthday Coming"),
                    ("inactive_reminder", "Inactive Reminder"),
                    ("milestone_reached", "Milestone Reached"),
                    ("points_threshold", "Points Threshold"),
                    ("scheduled_time", "Scheduled Time"),
                ],
                help_text="Trigger.",
                max_length=30,
                verbose_name="Disparador",
            ),
        ),
        migrations.AlterField(
            model_name="automation",
            name="trigger_config",
            field=models.JSONField(
                default=dict,
                help_text="Trigger configuration stored as JSON.",
                verbose_name="Configuración del disparador",
            ),
        ),
        migrations.AlterField(
            model_name="automationexecution",
            name="automation",
            field=models.ForeignKey(
                help_text="The automation rule that was executed.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="executions",
                to="automation.automation",
                verbose_name="Automatización",
            ),
        ),
        migrations.AlterField(
            model_name="automationexecution",
            name="customer",
            field=models.ForeignKey(
                help_text="The customer associated with this record.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="automation_executions",
                to="customers.customer",
                verbose_name="Cliente",
            ),
        ),
        migrations.AlterField(
            model_name="automationexecution",
            name="executed_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Timestamp when this execution occurred."
            ),
        ),
        migrations.AlterField(
            model_name="automationexecution",
            name="execution_context",
            field=models.JSONField(
                default=dict,
                help_text="Execution context stored as JSON.",
                verbose_name="Contexto de ejecución",
            ),
        ),
        migrations.AlterField(
            model_name="automationexecution",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Unique identifier for this record.",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="automationexecution",
            name="success",
            field=models.BooleanField(
                help_text="Whether the execution or operation succeeded.",
                verbose_name="Éxito",
            ),
        ),
        migrations.AlterField(
            model_name="automationexecution",
            name="trigger_event",
            field=models.CharField(
                help_text="Event that triggered this execution.",
                max_length=50,
                verbose_name="Evento disparador",
            ),
        ),
    ]
