# Generated by Django 5.0.6 on 2026-04-06 15:16

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Correo electrónico')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='Teléfono')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], default='', max_length=1, verbose_name='Género')),
                ('referral_code', models.CharField(blank=True, default='', max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Cliente activo')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notas')),
                ('total_visits', models.PositiveIntegerField(default=0, verbose_name='Total de visitas')),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total gastado')),
                ('last_visit', models.DateTimeField(blank=True, null=True, verbose_name='Última visita')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('referred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='customers.customer', verbose_name='Referido por')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='tenants.tenant', verbose_name='Negocio')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'loyallia_customers',
                'ordering': ['-created_at'],
                'unique_together': {('tenant', 'email')},
            },
        ),
        migrations.CreateModel(
            name='CustomerPass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pass_data', models.JSONField(default=dict, verbose_name='Datos del pase')),
                ('apple_pass_id', models.CharField(blank=True, default='', max_length=100, verbose_name='Apple Pass ID')),
                ('google_pass_id', models.CharField(blank=True, default='', max_length=100, verbose_name='Google Pass ID')),
                ('qr_code', models.CharField(blank=True, default='', max_length=100, unique=True, verbose_name='Código QR')),
                ('is_active', models.BooleanField(default=True, verbose_name='Pase activo')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de inscripción')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passes', to='cards.card', verbose_name='Programa')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passes', to='customers.customer', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Pase del cliente',
                'verbose_name_plural': 'Pases de clientes',
                'db_table': 'loyallia_customer_passes',
                'ordering': ['-enrolled_at'],
                'unique_together': {('customer', 'card')},
            },
        ),
    ]
