# Generated by Django 5.0.6 on 2026-04-22 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customerpass_qr_code'),
        ('tenants', '0004_tenant_default_language'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['tenant', 'created_at'], name='idx_cust_tenant_created'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['tenant', 'is_active', 'created_at'], name='idx_cust_tenant_active_date'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['tenant', 'date_of_birth'], name='idx_cust_tenant_dob'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['tenant', 'last_name', 'first_name'], name='idx_cust_tenant_name'),
        ),
    ]
