# Generated by Django 5.0.6 on 2026-05-01 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0004_customerpass_idx_pass_card_active"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="customerpass",
            name="idx_pass_card_active",
        ),
        migrations.AddField(
            model_name="customerpass",
            name="cashback_balance",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                verbose_name="Balance de cashback",
            ),
        ),
        migrations.AddField(
            model_name="customerpass",
            name="gift_balance",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                verbose_name="Balance de certificado de regalo",
            ),
        ),
        migrations.AddField(
            model_name="customerpass",
            name="multipass_remaining",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Usos restantes multipase"
            ),
        ),
        migrations.AddField(
            model_name="customerpass",
            name="referral_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Contador de referidos"
            ),
        ),
        migrations.AddField(
            model_name="customerpass",
            name="stamp_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Contador de sellos"
            ),
        ),
    ]
