# Generated by Django 5.0.6 on 2026-05-18 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0006_remove_card_idx_card_tenant_active"),
        ("customers", "0006_apple_pass_registration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerpass",
            name="card",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="passes",
                to="cards.card",
                verbose_name="Programa",
            ),
        ),
    ]
