# Generated by Django 5.0.6 on 2026-05-19 19:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_alter_customerpass_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPortalAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('password', models.CharField(blank=True, default='', max_length=128, verbose_name='Contraseña')),
                ('is_active', models.BooleanField(default=True, verbose_name='Cuenta activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cuenta de Portal de Cliente',
                'verbose_name_plural': 'Cuentas de Portal de Clientes',
                'db_table': 'loyallia_customer_portal_accounts',
            },
        ),
    ]
