# Generated by Django 5.2.14 on 2026-06-03 20:35

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0010_alter_card_background_color_alter_card_barcode_type_and_more'),
        ('customers', '0009_customerpass_coupon_redemption_count_and_more'),
        ('tenants', '0011_alter_location_address_alter_location_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applepassregistration',
            name='customer_pass',
            field=models.ForeignKey(help_text='The customer loyalty pass.', on_delete=django.db.models.deletion.CASCADE, related_name='apple_registrations', to='customers.customerpass', verbose_name='Customer Pass'),
        ),
        migrations.AlterField(
            model_name='applepassregistration',
            name='device_library_id',
            field=models.CharField(db_index=True, help_text='Apple device identifier.', max_length=255, verbose_name='Device Library Identifier'),
        ),
        migrations.AlterField(
            model_name='applepassregistration',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='applepassregistration',
            name='push_token',
            field=models.CharField(help_text='APNs push token for pass updates.', max_length=255, verbose_name='APNs Push Token'),
        ),
        migrations.AlterField(
            model_name='applepassregistration',
            name='registered_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp for registered.'),
        ),
        migrations.AlterField(
            model_name='applepassregistration',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp for updated.'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Date of birth.', null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(help_text='Email address.', max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(help_text='First name.', max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], default='', help_text='Gender.', max_length=1, verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this record is currently active.', verbose_name='Cliente activo'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(help_text='Last name.', max_length=100, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_visit',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the last visit.', null=True, verbose_name='Última visita'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Additional notes or comments.', verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, default='', help_text='Phone number.', max_length=20, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='referral_code',
            field=models.CharField(blank=True, default='', help_text='Unique referral code.', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='referred_by',
            field=models.ForeignKey(blank=True, help_text='Customer who referred this person.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='customers.customer', verbose_name='Referido por'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='tenant',
            field=models.ForeignKey(help_text='The business this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='tenants.tenant', verbose_name='Negocio'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='total_spent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total amount spent.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total gastado'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='total_visits',
            field=models.PositiveIntegerField(default=0, help_text='Total number of visits recorded.', verbose_name='Total de visitas'),
        ),
        migrations.AlterField(
            model_name='customerpass',
            name='apple_pass_id',
            field=models.CharField(blank=True, default='', help_text='Identifier for the Apple Wallet pass.', max_length=100, verbose_name='Apple Pass ID'),
        ),
        migrations.AlterField(
            model_name='customerpass',
            name='card',
            field=models.ForeignKey(help_text='The loyalty program associated with this record.', on_delete=django.db.models.deletion.PROTECT, related_name='passes', to='cards.card', verbose_name='Programa'),
        ),
        migrations.AlterField(
            model_name='customerpass',
            name='cashback_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Current balance.', max_digits=12, verbose_name='Balance de cashback'),
        ),
        migrations.AlterField(
            model_name='customerpass',
            name='coupon_redemption_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times the coupon was redeemed.', verbose_name='Contador de canjes de cupón'),
        ),
        migrations.AlterField(
            model_name='customerpass',
            name='customer',
            field=models.ForeignKey(help_text='The customer associated with this record.', on_delete=django.db.models.deletion.CASCADE, related_name='passes', to='customers.customer', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='customerpass',
            name='enrolled_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp for enrolled.', verbose_name='Fecha de inscripción'),
        ),
        migrations.AlterField(
            model_name='customerpass',
            name='gift_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Current gift certificate balance.', max_digits=12, verbose_name='Balance de certificado de regalo'),
        ),
        migrations.AlterField(
            model_name='customerpass',
            name='google_pass_id',
            field=models.CharField(blank=True, default='', help_text='Identifier for the Google Wallet pass.', max_length=100, verbose_name='Google Pass ID'),
        ),
        migrations.AlterField(
            model_name='customerpass',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerpass',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this record is currently active.', verbose_name='Pase activo'),
        ),
        migrations.AlterField(
            model_name='customerpass',
            name='last_redemption_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp for last redemption.', null=True, verbose_name='Último canje'),
        ),
        migrations.AlterField(
            model_name='customerpass',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, help_text='Last updated.', verbose_name='Última actualización'),
        ),
        migrations.AlterField(
            model_name='customerpass',
            name='lifecycle_state',
            field=models.CharField(choices=[('active', 'Activo'), ('reward_ready', 'Recompensa lista'), ('expired', 'Expirado'), ('depleted', 'Agotado'), ('suspended', 'Suspendido')], default='active', help_text='Current lifecycle state of the pass.', max_length=20, verbose_name='Estado del ciclo de vida'),
        ),
        migrations.AlterField(
            model_name='customerpass',
            name='multipass_remaining',
            field=models.PositiveIntegerField(default=0, help_text='Remaining uses in the multipass.', verbose_name='Usos restantes multipase'),
        ),
        migrations.AlterField(
            model_name='customerpass',
            name='pass_data',
            field=models.JSONField(default=dict, help_text='Pass state data stored as JSON.', verbose_name='Datos del pase'),
        ),
        migrations.AlterField(
            model_name='customerpass',
            name='pending_rewards',
            field=models.JSONField(default=list, help_text='Queue of pending rewards.', verbose_name='Recompensas pendientes'),
        ),
        migrations.AlterField(
            model_name='customerpass',
            name='qr_code',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Unique QR code for pass validation.', max_length=100, unique=True, verbose_name='Código QR'),
        ),
        migrations.AlterField(
            model_name='customerpass',
            name='referral_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of successful referrals.', verbose_name='Contador de referidos'),
        ),
        migrations.AlterField(
            model_name='customerpass',
            name='stamp_count',
            field=models.PositiveIntegerField(default=0, help_text='Current stamp count.', verbose_name='Contador de sellos'),
        ),
        migrations.AlterField(
            model_name='customerportalaccount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp for created.'),
        ),
        migrations.AlterField(
            model_name='customerportalaccount',
            name='email',
            field=models.EmailField(help_text='Email address.', max_length=254, unique=True, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='customerportalaccount',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerportalaccount',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this record is currently active.', verbose_name='Cuenta activa'),
        ),
        migrations.AlterField(
            model_name='customerportalaccount',
            name='password',
            field=models.CharField(blank=True, default='', help_text='Password or credential.', max_length=128, verbose_name='Contraseña'),
        ),
        migrations.AlterField(
            model_name='customerportalaccount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp for updated.'),
        ),
    ]
