# Generated by Django 5.2.14 on 2026-06-03 20:44

from django.db import migrations


def populate_tenant(apps, schema_editor):
    """Populate CustomerPass.tenant from Customer.tenant for existing rows."""
    CustomerPass = apps.get_model("customers", "CustomerPass")
    for cp in CustomerPass.objects.filter(tenant__isnull=True).select_related("customer"):
        cp.tenant_id = cp.customer.tenant_id
        cp.save(update_fields=["tenant_id"])


def reverse_populate(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0011_alter_customer_unique_together_and_more"),
    ]

    operations = [
        migrations.RunPython(populate_tenant, reverse_populate),
    ]
