# Generated by Django 5.0.6 on 2026-04-06 15:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Nombre del negocio"),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=100, unique=True, verbose_name="Slug único"
                    ),
                ),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("trial", "Trial Gratuito"),
                            ("full", "FULL"),
                            ("suspended", "Suspendido"),
                        ],
                        default="trial",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("trial_end", models.DateTimeField(blank=True, null=True)),
                ("logo_url", models.URLField(blank=True, default="")),
                ("primary_color", models.CharField(default="#1a1a2e", max_length=7)),
                ("secondary_color", models.CharField(default="#16213e", max_length=7)),
                ("country", models.CharField(default="EC", max_length=2)),
                (
                    "timezone",
                    models.CharField(default="America/Guayaquil", max_length=50),
                ),
                ("phone", models.CharField(blank=True, default="", max_length=20)),
                ("website", models.URLField(blank=True, default="")),
                ("address", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Negocio",
                "verbose_name_plural": "Negocios",
                "db_table": "loyallia_tenants",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("address", models.TextField(blank=True, default="")),
                ("city", models.CharField(blank=True, default="", max_length=100)),
                ("country", models.CharField(default="EC", max_length=2)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("phone", models.CharField(blank=True, default="", max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("is_primary", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ubicación",
                "verbose_name_plural": "Ubicaciones",
                "db_table": "loyallia_locations",
                "ordering": ["-is_primary", "name"],
            },
        ),
    ]
