# Generated by Django 5.0.6 on 2026-04-07 14:44

import apps.tenants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Email corporativo'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='industry',
            field=models.CharField(choices=[('food_beverage', 'Alimentos y Bebidas'), ('retail', 'Comercio Minorista'), ('fashion', 'Moda y Textiles'), ('health_beauty', 'Salud y Belleza'), ('entertainment', 'Entretenimiento'), ('services', 'Servicios Profesionales'), ('education', 'Educación'), ('automotive', 'Automotriz'), ('hospitality', 'Hotelería y Turismo'), ('technology', 'Tecnología'), ('other', 'Otro')], default='other', max_length=30, verbose_name='Industria'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='legal_name',
            field=models.CharField(blank=True, default='', help_text='Nombre legal registrado en SRI', max_length=300, verbose_name='Razón social'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='legal_rep_cedula',
            field=models.CharField(blank=True, default='', max_length=10, validators=[apps.tenants.models.validate_cedula], verbose_name='Cédula del representante'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='legal_rep_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Representante legal'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='province',
            field=models.CharField(blank=True, choices=[('azuay', 'Azuay'), ('bolivar', 'Bolívar'), ('canar', 'Cañar'), ('carchi', 'Carchi'), ('chimborazo', 'Chimborazo'), ('cotopaxi', 'Cotopaxi'), ('el_oro', 'El Oro'), ('esmeraldas', 'Esmeraldas'), ('galapagos', 'Galápagos'), ('guayas', 'Guayas'), ('imbabura', 'Imbabura'), ('loja', 'Loja'), ('los_rios', 'Los Ríos'), ('manabi', 'Manabí'), ('morona_santiago', 'Morona Santiago'), ('napo', 'Napo'), ('orellana', 'Orellana'), ('pastaza', 'Pastaza'), ('pichincha', 'Pichincha'), ('santa_elena', 'Santa Elena'), ('santo_domingo', 'Santo Domingo de los Tsáchilas'), ('sucumbios', 'Sucumbíos'), ('tungurahua', 'Tungurahua'), ('zamora_chinchipe', 'Zamora Chinchipe')], default='', max_length=30, verbose_name='Provincia'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='ruc',
            field=models.CharField(blank=True, default='', help_text='Registro Único de Contribuyentes (13 dígitos)', max_length=13, validators=[apps.tenants.models.validate_ruc], verbose_name='RUC'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre comercial'),
        ),
    ]
