# Generated by Django 5.0.6 on 2026-04-22 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_add_entity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='default_language',
            field=models.CharField(default='es', help_text='ISO 639-1: es, en, fr, de. Set at tenant registration.', max_length=5, verbose_name='Idioma predeterminado'),
        ),
    ]
