# Generated by Django 4.2.30 on 2026-05-08 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0006_tenant_scheduled_deletion_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenant",
            name="scheduled_deletion_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When set, Celery will hard-delete all tenant data after this timestamp.",
                null=True,
                verbose_name="Eliminación programada",
            ),
        ),
    ]
