# Generated by Django 5.0.6 on 2026-05-18 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0009_alter_tenant_scheduled_deletion_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='logo_url',
            field=models.URLField(blank=True, default='', max_length=2000),
        ),
    ]
