# Generated by Django 5.2.15 on 2026-09-29 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0012_platformsetting_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenant",
            name="slug",
            field=models.SlugField(
                blank=True,
                default="",
                help_text="URL-friendly unique identifier. Auto-generated from name when blank.",
                max_length=100,
                unique=True,
                verbose_name="Slug único",
            ),
        ),
    ]
