/**
 * Dynamic value templates for the Wallet Pass Studio.
 */

import type { CardType } from './unified-state';

export interface DynamicTemplate {
  id: string;
  label: string;
  description: string;
  exampleValue: string;
  applicableCardTypes: CardType[];
}

export const DYNAMIC_TEMPLATES: DynamicTemplate[] = [
  {
    id: 'customer_name',
    label: 'Customer Name',
    description: 'Full name of the pass holder',
    exampleValue: 'John Doe',
    applicableCardTypes: [
      'stamp',
      'cashback',
      'coupon',
      'affiliate',
      'discount',
      'gift_certificate',
      'vip_membership',
      'corporate_discount',
      'referral_pass',
      'multipass',
    ],
  },
  {
    id: 'stamp_count',
    label: 'Stamp Count',
    description: 'Current number of stamps collected',
    exampleValue: '7',
    applicableCardTypes: ['stamp'],
  },
  {
    id: 'points_balance',
    label: 'Points Balance',
    description: 'Current loyalty points balance',
    exampleValue: '1,250',
    applicableCardTypes: ['cashback', 'discount', 'vip_membership'],
  },
  {
    id: 'tier_name',
    label: 'Tier Name',
    description: 'Current membership tier',
    exampleValue: 'Gold',
    applicableCardTypes: ['discount', 'vip_membership', 'cashback'],
  },
  {
    id: 'membership_id',
    label: 'Membership ID',
    description: 'Unique membership identifier',
    exampleValue: 'MEM-12345678',
    applicableCardTypes: [
      'stamp',
      'cashback',
      'coupon',
      'vip_membership',
      'corporate_discount',
      'multipass',
    ],
  },
  {
    id: 'reward_description',
    label: 'Reward Description',
    description: 'Description of the available reward',
    exampleValue: 'Free Coffee',
    applicableCardTypes: ['stamp', 'cashback', 'coupon', 'gift_certificate'],
  },
  {
    id: 'expiration_date',
    label: 'Expiration Date',
    description: 'Date when the pass or offer expires',
    exampleValue: '2025-12-31',
    applicableCardTypes: ['coupon', 'gift_certificate', 'referral_pass', 'multipass'],
  },
  {
    id: 'barcode_data',
    label: 'Barcode Data',
    description: 'Raw data encoded in the barcode',
    exampleValue: '1234567890123',
    applicableCardTypes: [
      'stamp',
      'cashback',
      'coupon',
      'affiliate',
      'discount',
      'gift_certificate',
      'vip_membership',
      'corporate_discount',
      'referral_pass',
      'multipass',
    ],
  },
  {
    id: 'qr_code',
    label: 'QR Code',
    description: 'Data encoded in the QR code',
    exampleValue: 'https://loyallia.com/r/abc123',
    applicableCardTypes: [
      'stamp',
      'cashback',
      'coupon',
      'affiliate',
      'discount',
      'gift_certificate',
      'vip_membership',
      'corporate_discount',
      'referral_pass',
      'multipass',
    ],
  },
  {
    id: 'program_name',
    label: 'Program Name',
    description: 'Name of the loyalty program',
    exampleValue: 'Loyallia Rewards',
    applicableCardTypes: [
      'stamp',
      'cashback',
      'coupon',
      'affiliate',
      'discount',
      'vip_membership',
      'corporate_discount',
      'multipass',
    ],
  },
  {
    id: 'merchant_name',
    label: 'Merchant Name',
    description: 'Name of the business or merchant',
    exampleValue: 'Acme Coffee',
    applicableCardTypes: [
      'stamp',
      'cashback',
      'coupon',
      'affiliate',
      'discount',
      'gift_certificate',
      'vip_membership',
      'corporate_discount',
      'multipass',
    ],
  },
  {
    id: 'current_date',
    label: 'Current Date',
    description: "Today's date, dynamically generated",
    exampleValue: '2025-01-15',
    applicableCardTypes: [
      'stamp',
      'cashback',
      'coupon',
      'affiliate',
      'discount',
      'gift_certificate',
      'vip_membership',
      'corporate_discount',
      'referral_pass',
      'multipass',
    ],
  },
  {
    id: 'visit_count',
    label: 'Visit Count',
    description: 'Total number of customer visits',
    exampleValue: '42',
    applicableCardTypes: ['stamp', 'cashback', 'multipass'],
  },
  {
    id: 'purchase_total',
    label: 'Purchase Total',
    description: 'Total amount of the current or last purchase',
    exampleValue: '$45.67',
    applicableCardTypes: ['cashback', 'discount', 'coupon', 'gift_certificate'],
  },
  {
    id: 'discount_amount',
    label: 'Discount Amount',
    description: 'Calculated discount value',
    exampleValue: '$10.00',
    applicableCardTypes: ['coupon', 'discount', 'corporate_discount', 'gift_certificate'],
  },
  {
    id: 'cashback_earned',
    label: 'Cashback Earned',
    description: 'Total cashback earned to date',
    exampleValue: '$125.50',
    applicableCardTypes: ['cashback'],
  },
  {
    id: 'referral_code',
    label: 'Referral Code',
    description: "Customer's unique referral code",
    exampleValue: 'FRIEND20',
    applicableCardTypes: ['referral_pass', 'affiliate'],
  },
  {
    id: 'friend_name',
    label: 'Friend Name',
    description: 'Name of the referred friend',
    exampleValue: 'Jane Smith',
    applicableCardTypes: ['referral_pass'],
  },
  {
    id: 'gift_amount',
    label: 'Gift Amount',
    description: 'Remaining gift certificate balance',
    exampleValue: '$50.00',
    applicableCardTypes: ['gift_certificate'],
  },
  {
    id: 'remaining_uses',
    label: 'Remaining Uses',
    description: 'Number of uses left on a multi-use pass',
    exampleValue: '3',
    applicableCardTypes: ['multipass', 'coupon'],
  },
  {
    id: 'session_count',
    label: 'Session Count',
    description: 'Number of sessions or entries used',
    exampleValue: '5',
    applicableCardTypes: ['multipass'],
  },
  {
    id: 'employee_id',
    label: 'Employee ID',
    description: 'Corporate employee identifier',
    exampleValue: 'EMP-98765',
    applicableCardTypes: ['corporate_discount'],
  },
  {
    id: 'department',
    label: 'Department',
    description: 'Employee department name',
    exampleValue: 'Engineering',
    applicableCardTypes: ['corporate_discount'],
  },
  {
    id: 'company_name',
    label: 'Company Name',
    description: 'Name of the employer or company',
    exampleValue: 'TechCorp Inc.',
    applicableCardTypes: ['corporate_discount', 'affiliate'],
  },
  {
    id: 'phone_number',
    label: 'Phone Number',
    description: 'Customer contact phone number',
    exampleValue: '+1 (555) 123-4567',
    applicableCardTypes: [
      'stamp',
      'cashback',
      'coupon',
      'affiliate',
      'discount',
      'gift_certificate',
      'vip_membership',
      'corporate_discount',
      'referral_pass',
      'multipass',
    ],
  },
  {
    id: 'email_address',
    label: 'Email Address',
    description: 'Customer contact email address',
    exampleValue: 'john.doe@example.com',
    applicableCardTypes: [
      'stamp',
      'cashback',
      'coupon',
      'affiliate',
      'discount',
      'gift_certificate',
      'vip_membership',
      'corporate_discount',
      'referral_pass',
      'multipass',
    ],
  },
];

export function getDynamicTemplatesForCardType(cardType: CardType): DynamicTemplate[] {
  return DYNAMIC_TEMPLATES.filter((template) => template.applicableCardTypes.includes(cardType));
}
