# Generated by Django 5.0.6 on 2026-05-18 22:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0009_alter_tenant_scheduled_deletion_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('running', 'running'), ('completed', 'completed'), ('failed', 'failed'), ('verified', 'verified'), ('corrupted', 'corrupted')], db_index=True, default='pending', max_length=20)),
                ('backup_type', models.CharField(choices=[('full', 'full'), ('incremental', 'incremental'), ('manual', 'manual')], default='full', max_length=20)),
                ('include_media', models.BooleanField(default=True)),
                ('include_vault', models.BooleanField(default=True)),
                ('encryption_enabled', models.BooleanField(default=True)),
                ('compression_enabled', models.BooleanField(default=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('file_path', models.CharField(blank=True, default='', max_length=500)),
                ('s3_key', models.CharField(blank=True, default='', max_length=500)),
                ('verification_status', models.CharField(default='pending', max_length=20)),
                ('verification_details', models.TextField(blank=True, default='')),
                ('error_message', models.TextField(blank=True, default='')),
                ('retry_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, help_text='Null for platform-level backups (SuperAdmin scope).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='backup_jobs', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Backup Job',
                'verbose_name_plural': 'Backup Jobs',
                'db_table': 'backup_jobs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'status', 'created_at'], name='backup_jobs_tenant__9f00e4_idx'), models.Index(fields=['backup_type', 'status'], name='backup_jobs_backup__fbee91_idx'), models.Index(fields=['verification_status', 'created_at'], name='backup_jobs_verific_e4d031_idx')],
            },
        ),
    ]
