# Generated by Django 5.2.14 on 2026-06-03 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backup", "0003_alter_backupjob_table"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="backupjob",
            new_name="loyallia_ba_tenant__59508f_idx",
            old_name="backup_jobs_tenant__9f00e4_idx",
        ),
        migrations.RenameIndex(
            model_name="backupjob",
            new_name="loyallia_ba_backup__ed410c_idx",
            old_name="backup_jobs_backup__fbee91_idx",
        ),
        migrations.RenameIndex(
            model_name="backupjob",
            new_name="loyallia_ba_verific_094680_idx",
            old_name="backup_jobs_verific_e4d031_idx",
        ),
    ]
