/**
 * Auto-generated Lucide icon mapping for the Wallet Pass Studio.
 * Imports all Lucide icons referenced in icon-library.ts.
 */
import React from 'react';
import type { LucideProps } from 'lucide-react';
import {
  Activity,
  Ambulance,
  Apple,
  Award,
  Baby,
  Badge,
  BadgeCheck,
  BadgeDollarSign,
  BadgePercent,
  Banana,
  Banknote,
  BarChart3,
  Battery,
  BatteryCharging,
  Beef,
  Beer,
  Bell,
  Bike,
  Bluetooth,
  Bone,
  Bookmark,
  Brain,
  Building2,
  Bus,
  Cake,
  Calculator,
  Calendar,
  Camera,
  Car,
  Carrot,
  CheckCircle,
  Cherry,
  Circle,
  Clock,
  Cloud,
  CloudLightning,
  CloudRain,
  CloudSnow,
  Coffee,
  Coins,
  Compass,
  Cookie,
  CookingPot,
  Cpu,
  CreditCard,
  Croissant,
  Crown,
  CupSoda,
  Diamond,
  Dna,
  DollarSign,
  Donut,
  Droplet,
  Droplets,
  Ear,
  Egg,
  Euro,
  Eye,
  Film,
  Fish,
  Flag,
  Flame,
  Flower2,
  Footprints,
  Frown,
  Fuel,
  Gamepad2,
  Gauge,
  Gem,
  Gift,
  Glasses,
  HardDrive,
  Headphones,
  Heart,
  HeartPulse,
  Hexagon,
  Hospital,
  IceCreamCone,
  Image,
  JapaneseYen,
  Keyboard,
  Landmark,
  Laptop,
  Leaf,
  LineChart,
  Locate,
  Mail,
  Map,
  MapPin,
  Medal,
  Meh,
  MessageCircle,
  Mic,
  Microscope,
  Microwave,
  Monitor,
  Moon,
  Mountain,
  Mouse,
  Music,
  Navigation,
  Octagon,
  Package,
  Paintbrush,
  Palette,
  ParkingSquare,
  Pen,
  Pentagon,
  Percent,
  Phone,
  PieChart,
  PiggyBank,
  Pill,
  Pin,
  Pizza,
  Plane,
  Plug,
  PoundSterling,
  Printer,
  Radio,
  Rainbow,
  Receipt,
  Ribbon,
  Route,
  Sailboat,
  Salad,
  Sandwich,
  Scale,
  Scissors,
  Share2,
  Shield,
  ShieldAlert,
  ShieldCheck,
  ShieldPlus,
  ShieldQuestion,
  Ship,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Smile,
  Snowflake,
  Soup,
  Sparkles,
  Square,
  Star,
  Stethoscope,
  Store,
  Sun,
  Sunrise,
  Sunset,
  Tablet,
  Tag,
  Thermometer,
  ThermometerSun,
  ThumbsUp,
  Ticket,
  Timer,
  TrafficCone,
  TrainFront,
  TreePine,
  TrendingDown,
  TrendingUp,
  Triangle,
  Trophy,
  Truck,
  Tv,
  Type,
  User,
  UserCheck,
  UserCircle,
  UserPlus,
  Users,
  Utensils,
  UtensilsCrossed,
  Video,
  Wallet,
  Watch,
  Waves,
  Wifi,
  Wind,
  Wine,
  XCircle,
  Zap,
} from 'lucide-react';

export const LUCIDE_ICON_MAP: Record<string, React.ComponentType<LucideProps>> = {
    Activity: Activity,
    Ambulance: Ambulance,
    Apple: Apple,
    Award: Award,
    Baby: Baby,
    Badge: Badge,
    BadgeCheck: BadgeCheck,
    BadgeDollarSign: BadgeDollarSign,
    BadgePercent: BadgePercent,
    Banana: Banana,
    Banknote: Banknote,
    BarChart3: BarChart3,
    Battery: Battery,
    BatteryCharging: BatteryCharging,
    Beef: Beef,
    Beer: Beer,
    Bell: Bell,
    Bike: Bike,
    Bluetooth: Bluetooth,
    Bone: Bone,
    Bookmark: Bookmark,
    Brain: Brain,
    Building2: Building2,
    Bus: Bus,
    Cake: Cake,
    Calculator: Calculator,
    Calendar: Calendar,
    Camera: Camera,
    Car: Car,
    Carrot: Carrot,
    CheckCircle: CheckCircle,
    Cherry: Cherry,
    Circle: Circle,
    Clock: Clock,
    Cloud: Cloud,
    CloudLightning: CloudLightning,
    CloudRain: CloudRain,
    CloudSnow: CloudSnow,
    Coffee: Coffee,
    Coins: Coins,
    Compass: Compass,
    Cookie: Cookie,
    CookingPot: CookingPot,
    Cpu: Cpu,
    CreditCard: CreditCard,
    Croissant: Croissant,
    Crown: Crown,
    CupSoda: CupSoda,
    Diamond: Diamond,
    Dna: Dna,
    DollarSign: DollarSign,
    Donut: Donut,
    Droplet: Droplet,
    Droplets: Droplets,
    Ear: Ear,
    Egg: Egg,
    Euro: Euro,
    Eye: Eye,
    Film: Film,
    Fish: Fish,
    Flag: Flag,
    Flame: Flame,
    Flower2: Flower2,
    Footprints: Footprints,
    Frown: Frown,
    Fuel: Fuel,
    Gamepad2: Gamepad2,
    Gauge: Gauge,
    Gem: Gem,
    Gift: Gift,
    Glasses: Glasses,
    HardDrive: HardDrive,
    Headphones: Headphones,
    Heart: Heart,
    HeartPulse: HeartPulse,
    Hexagon: Hexagon,
    Hospital: Hospital,
    IceCreamCone: IceCreamCone,
    Image: Image,
    JapaneseYen: JapaneseYen,
    Keyboard: Keyboard,
    Landmark: Landmark,
    Laptop: Laptop,
    Leaf: Leaf,
    LineChart: LineChart,
    Locate: Locate,
    Mail: Mail,
    Map: Map,
    MapPin: MapPin,
    Medal: Medal,
    Meh: Meh,
    MessageCircle: MessageCircle,
    Mic: Mic,
    Microscope: Microscope,
    Microwave: Microwave,
    Monitor: Monitor,
    Moon: Moon,
    Mountain: Mountain,
    Mouse: Mouse,
    Music: Music,
    Navigation: Navigation,
    Octagon: Octagon,
    Package: Package,
    Paintbrush: Paintbrush,
    Palette: Palette,
    ParkingSquare: ParkingSquare,
    Pen: Pen,
    Pentagon: Pentagon,
    Percent: Percent,
    Phone: Phone,
    PieChart: PieChart,
    PiggyBank: PiggyBank,
    Pill: Pill,
    Pin: Pin,
    Pizza: Pizza,
    Plane: Plane,
    Plug: Plug,
    PoundSterling: PoundSterling,
    Printer: Printer,
    Radio: Radio,
    Rainbow: Rainbow,
    Receipt: Receipt,
    Ribbon: Ribbon,
    Route: Route,
    Sailboat: Sailboat,
    Salad: Salad,
    Sandwich: Sandwich,
    Scale: Scale,
    Scissors: Scissors,
    Share2: Share2,
    Shield: Shield,
    ShieldAlert: ShieldAlert,
    ShieldCheck: ShieldCheck,
    ShieldPlus: ShieldPlus,
    ShieldQuestion: ShieldQuestion,
    Ship: Ship,
    Shirt: Shirt,
    ShoppingBag: ShoppingBag,
    ShoppingCart: ShoppingCart,
    Smartphone: Smartphone,
    Smile: Smile,
    Snowflake: Snowflake,
    Soup: Soup,
    Sparkles: Sparkles,
    Square: Square,
    Star: Star,
    Stethoscope: Stethoscope,
    Store: Store,
    Sun: Sun,
    Sunrise: Sunrise,
    Sunset: Sunset,
    Tablet: Tablet,
    Tag: Tag,
    Thermometer: Thermometer,
    ThermometerSun: ThermometerSun,
    ThumbsUp: ThumbsUp,
    Ticket: Ticket,
    Timer: Timer,
    TrafficCone: TrafficCone,
    TrainFront: TrainFront,
    TreePine: TreePine,
    TrendingDown: TrendingDown,
    TrendingUp: TrendingUp,
    Triangle: Triangle,
    Trophy: Trophy,
    Truck: Truck,
    Tv: Tv,
    Type: Type,
    User: User,
    UserCheck: UserCheck,
    UserCircle: UserCircle,
    UserPlus: UserPlus,
    Users: Users,
    Utensils: Utensils,
    UtensilsCrossed: UtensilsCrossed,
    Video: Video,
    Wallet: Wallet,
    Watch: Watch,
    Waves: Waves,
    Wifi: Wifi,
    Wind: Wind,
    Wine: Wine,
    XCircle: XCircle,
    Zap: Zap,
};

export function getLucideIcon(name: string): React.ComponentType<LucideProps> | undefined {
  return LUCIDE_ICON_MAP[name];
}
