# Generated by Django 5.0.6 on 2026-04-22 03:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0004_tenant_default_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentAPIKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Descriptive name for this key (e.g., 'SOMA Agent Production')", max_length=100, verbose_name='Nombre de la clave')),
                ('key_hash', models.CharField(max_length=64, unique=True, verbose_name='Hash SHA-256')),
                ('key_prefix', models.CharField(help_text='First 8 characters for identification', max_length=8, verbose_name='Prefijo de clave')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='Último uso')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expira en')),
                ('created_by_id', models.UUIDField(verbose_name='Creado por (user_id)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_api_keys', to='tenants.tenant', verbose_name='Negocio')),
            ],
            options={
                'verbose_name': 'Clave de API (Agente)',
                'verbose_name_plural': 'Claves de API (Agentes)',
                'db_table': 'loyallia_agent_api_keys',
                'ordering': ['-created_at'],
            },
        ),
    ]
